Repository woowacourse-teams/2023-emmsale, pull requests merged in 2023-09, with the labels that each got.

#509 [Feat] EventInfoViewModel 테스트 구현
  android/2023-emmsale/app/build.gradle.kts
  android/2023-emmsale/app/src/test/java/com/emmsale/presentation/ui/eventdetail/EventDetailViewModelTest.kt
  android/2023-emmsale/app/src/test/java/com/emmsale/presentation/ui/eventdetail/information/EventInfoViewModelTest.kt
Labels: 안드로이드, Low Priority

#539 Feature/#518 행사 목록 화면 개선
  android/2023-emmsale/app/src/main/java/com/emmsale/data/event/dto/CompetitionApiModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/event/dto/ConferenceApiModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/event/mapper/CompetitionMapper.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/event/mapper/ConferenceMapper.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/event/model/Competition.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/event/model/Conference.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/competition/CompetitionFragment.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/competition/recyclerview/CompetitionRecyclerViewDivider.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/competition/uistate/CompetitionSelectedFilteringUiState.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/competition/uistate/CompetitionUiState.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/conference/ConferenceFragment.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/conference/recyclerview/ConferenceRecyclerViewDivider.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/conference/uistate/ConferenceSelectedFilteringUiState.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/conference/uistate/ConferenceUiState.kt
  android/2023-emmsale/app/src/main/res/layout/fragment_competition.xml
  android/2023-emmsale/app/src/main/res/layout/fragment_conference.xml
  android/2023-emmsale/app/src/main/res/layout/item_competition.xml
  android/2023-emmsale/app/src/main/res/layout/item_conference.xml
  android/2023-emmsale/app/src/main/res/values/colors.xml
  android/2023-emmsale/app/src/main/res/values/strings.xml
Labels: 안드로이드, Low Priority

#523 Feature/#507 쪽지함에서 쪽지방 목록 조회
  backend/emm-sale/src/documentTest/asciidoc/index.adoc
  backend/emm-sale/src/documentTest/java/com/emmsale/MockMvcTestHelper.java
  backend/emm-sale/src/documentTest/java/com/emmsale/RoomApiTest.java
  backend/emm-sale/src/main/java/com/emmsale/message_room/api/RoomApi.java
  backend/emm-sale/src/main/java/com/emmsale/message_room/application/RoomCommandService.java
  backend/emm-sale/src/main/java/com/emmsale/message_room/application/RoomQueryService.java
  backend/emm-sale/src/main/java/com/emmsale/message_room/application/dto/RoomResponse.java
  backend/emm-sale/src/main/java/com/emmsale/message_room/domain/Message.java
  backend/emm-sale/src/main/java/com/emmsale/message_room/domain/MessageRepository.java
  backend/emm-sale/src/main/java/com/emmsale/message_room/domain/Room.java
  backend/emm-sale/src/main/java/com/emmsale/message_room/domain/RoomId.java
  backend/emm-sale/src/main/java/com/emmsale/message_room/domain/RoomRepository.java
  backend/emm-sale/src/main/java/com/emmsale/message_room/infrastructure/persistence/MessageDao.java
  backend/emm-sale/src/main/java/com/emmsale/message_room/infrastructure/persistence/dto/MessageOverview.java
  backend/emm-sale/src/main/resources/data.sql
  backend/emm-sale/src/main/resources/schema.sql
  backend/emm-sale/src/test/java/com/emmsale/message_room/application/RoomQueryServiceTest.java
  backend/emm-sale/src/test/java/com/emmsale/message_room/domain/RoomRepositoryTest.java
  backend/emm-sale/src/test/java/com/emmsale/message_room/infrastructure/persistence/MessageDaoTest.java
  backend/emm-sale/src/test/resources/data-test.sql
Labels: 백엔드, 기능 추가

#525 Feature/#510 room에 쪽지 보내는 기능
  backend/emm-sale/src/documentTest/asciidoc/index.adoc
  backend/emm-sale/src/documentTest/java/com/emmsale/MessagesApiTest.java
  backend/emm-sale/src/documentTest/java/com/emmsale/MockMvcTestHelper.java
  backend/emm-sale/src/main/java/com/emmsale/message_room/api/MessagesApi.java
  backend/emm-sale/src/main/java/com/emmsale/message_room/application/MessageCommandService.java
  backend/emm-sale/src/main/java/com/emmsale/message_room/application/dto/MessageSendRequest.java
  backend/emm-sale/src/main/java/com/emmsale/message_room/exception/MessageException.java
  backend/emm-sale/src/main/java/com/emmsale/message_room/exception/MessageExceptionType.java
  backend/emm-sale/src/main/resources/http/message.http
  backend/emm-sale/src/test/java/com/emmsale/message_room/application/MessageCommandServiceTest.java
Labels: 백엔드, 기능 추가

#538 Feature/#441 알림 종류 별 수신 설정
  android/2023-emmsale/app/src/main/java/com/emmsale/data/config/Config.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/config/ConfigRepository.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/config/ConfigRepositoryImpl.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/KerdyApplication.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/extension/ContextExt.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/viewModel/Refreshable.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/views/ConfirmDialog.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/service/KerdyFirebaseMessagingService.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/EventDetailViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/CommentViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/childComment/ChildCommentViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/information/EventInfoViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/recruitment/EventRecruitmentViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/recruitment/detail/RecruitmentPostDetailViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/competition/CompetitionViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/conference/ConferenceViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/scrap/ScrappedEventViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/myProfile/MyProfileViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/myProfile/editMyProfile/EditMyProfileViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/setting/SettingFragment.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/setting/SettingViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/setting/block/MemberBlockViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/setting/myComments/MyCommentsViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/setting/myPost/MyPostViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/setting/notification/NotificationConfigActivity.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/setting/notification/NotificationConfigViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/setting/notification/uistate/NotificationConfigUiEvent.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/setting/notification/uistate/NotificationConfigUiState.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/setting/notification/uistate/NotificationTagsUiState.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/setting/notificationTagConfig/NotificationTagConfigViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/notificationBox/primaryNotification/PrimaryNotificationViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/notificationBox/recruitmentNotification/RecruitmentNotificationViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/profile/ProfileViewModel.kt
  android/2023-emmsale/app/src/main/res/layout/activity_notification_config.xml
  android/2023-emmsale/app/src/main/res/layout/layout_all_error_screen.xml
  android/2023-emmsale/app/src/main/res/values/ids.xml
  android/2023-emmsale/app/src/main/res/values/strings.xml
Labels: 안드로이드, 기능 추가

#541 Feature/#524 쪽지 보낼 때 푸시 알림 보내는 기능
  backend/emm-sale/src/main/java/com/emmsale/GlobalControllerAdvice.java
  backend/emm-sale/src/main/java/com/emmsale/event_publisher/EventPublisher.java
  backend/emm-sale/src/main/java/com/emmsale/event_publisher/MessageNotificationEvent.java
  backend/emm-sale/src/main/java/com/emmsale/message_room/application/MessageCommandService.java
  backend/emm-sale/src/main/java/com/emmsale/message_room/exception/MessageException.java
  backend/emm-sale/src/main/java/com/emmsale/message_room/exception/MessageExceptionType.java
  backend/emm-sale/src/main/java/com/emmsale/message_room/exception/MessageRoomExceptionType.java
  backend/emm-sale/src/main/java/com/emmsale/notification/application/FirebaseCloudMessageClient.java
  backend/emm-sale/src/main/java/com/emmsale/notification/application/NotificationEventListener.java
  backend/emm-sale/src/main/java/com/emmsale/notification/application/dto/MessageNotificationMessage.java
  backend/emm-sale/src/main/java/com/emmsale/notification/application/generator/MessageNotificationMessageGenerator.java
  backend/emm-sale/src/test/java/com/emmsale/event_publisher/EventPublisherTest.java
  backend/emm-sale/src/test/java/com/emmsale/message_room/application/MessageCommandServiceTest.java
  backend/emm-sale/src/test/java/com/emmsale/notification/application/NotificationEventListenerTest.java
  backend/emm-sale/src/test/java/com/emmsale/notification/application/generator/MessageNotificationMessageGeneratorTest.java
Labels: 백엔드, 기능 추가, High Priority

#550 Feature/#549 기존 쪽지방에 쪽지 보내기
  backend/emm-sale/src/main/java/com/emmsale/message_room/application/MessageCommandService.java
  backend/emm-sale/src/main/java/com/emmsale/notification/application/dto/MessageNotificationMessage.java
  backend/emm-sale/src/main/java/com/emmsale/notification/application/generator/MessageNotificationMessageGenerator.java
  backend/emm-sale/src/test/java/com/emmsale/message_room/application/MessageCommandServiceTest.java
  backend/emm-sale/src/test/java/com/emmsale/notification/application/generator/MessageNotificationMessageGeneratorTest.java
Labels: 백엔드

#517 Feature/#499 피드 crud 기능 구현
  backend/emm-sale/src/documentTest/asciidoc/index.adoc
  backend/emm-sale/src/documentTest/java/com/emmsale/CommentApiTest.java
  backend/emm-sale/src/documentTest/java/com/emmsale/FeedApiTest.java
  backend/emm-sale/src/documentTest/java/com/emmsale/MockMvcTestHelper.java
  backend/emm-sale/src/documentTest/java/com/emmsale/UpdateNotificationApiTest.java
  backend/emm-sale/src/main/java/com/emmsale/comment/api/CommentApi.java
  backend/emm-sale/src/main/java/com/emmsale/comment/application/CommentCommandService.java
  backend/emm-sale/src/main/java/com/emmsale/comment/application/CommentQueryService.java
  backend/emm-sale/src/main/java/com/emmsale/comment/application/dto/CommentAddRequest.java
  backend/emm-sale/src/main/java/com/emmsale/comment/application/dto/CommentFindRequest.java
  backend/emm-sale/src/main/java/com/emmsale/comment/application/dto/CommentResponse.java
  backend/emm-sale/src/main/java/com/emmsale/comment/domain/Comment.java
  backend/emm-sale/src/main/java/com/emmsale/comment/domain/CommentRepository.java
  backend/emm-sale/src/main/java/com/emmsale/comment/exception/CommentExceptionType.java
  backend/emm-sale/src/main/java/com/emmsale/comment/infrastructure/persistence/CommentDao.java
  backend/emm-sale/src/main/java/com/emmsale/comment/infrastructure/persistence/dto/FeedCommentCount.java
  backend/emm-sale/src/main/java/com/emmsale/event/domain/Event.java
  backend/emm-sale/src/main/java/com/emmsale/feed/api/FeedApi.java
  backend/emm-sale/src/main/java/com/emmsale/feed/application/FeedCommandService.java
  backend/emm-sale/src/main/java/com/emmsale/feed/application/FeedQueryService.java
  backend/emm-sale/src/main/java/com/emmsale/feed/application/dto/FeedDetailResponse.java
  backend/emm-sale/src/main/java/com/emmsale/feed/application/dto/FeedListResponse.java
  backend/emm-sale/src/main/java/com/emmsale/feed/application/dto/FeedPostRequest.java
  backend/emm-sale/src/main/java/com/emmsale/feed/application/dto/FeedPostResponse.java
  backend/emm-sale/src/main/java/com/emmsale/feed/application/dto/FeedSimpleResponse.java
  backend/emm-sale/src/main/java/com/emmsale/feed/application/dto/FeedUpdateRequest.java
  backend/emm-sale/src/main/java/com/emmsale/feed/application/dto/FeedUpdateResponse.java
  backend/emm-sale/src/main/java/com/emmsale/feed/domain/Feed.java
  backend/emm-sale/src/main/java/com/emmsale/feed/domain/repository/FeedRepository.java
  backend/emm-sale/src/main/java/com/emmsale/feed/exception/FeedException.java
  backend/emm-sale/src/main/java/com/emmsale/feed/exception/FeedExceptionType.java
  backend/emm-sale/src/main/java/com/emmsale/image/application/S3Client.java
  backend/emm-sale/src/main/java/com/emmsale/notification/application/dto/UpdateNotificationResponse.java
  backend/emm-sale/src/main/resources/data.sql
  backend/emm-sale/src/main/resources/http/feed.http
  backend/emm-sale/src/main/resources/schema.sql
  backend/emm-sale/src/main/resources/static/docs/index.html
  backend/emm-sale/src/test/java/com/emmsale/comment/application/CommentCommandServiceEventIntegrationTest.java
  backend/emm-sale/src/test/java/com/emmsale/comment/application/CommentCommandServiceTest.java
  backend/emm-sale/src/test/java/com/emmsale/comment/application/CommentQueryServiceTest.java
  backend/emm-sale/src/test/java/com/emmsale/comment/domain/CommentRepositoryTest.java
  backend/emm-sale/src/test/java/com/emmsale/comment/domain/CommentTest.java
  backend/emm-sale/src/test/java/com/emmsale/comment/infrastructure/persistence/CommentDaoTest.java
  backend/emm-sale/src/test/java/com/emmsale/event_publisher/EventPublisherTest.java
  backend/emm-sale/src/test/java/com/emmsale/feed/application/FeedCommandServiceTest.java
  backend/emm-sale/src/test/java/com/emmsale/feed/application/FeedQueryServiceTest.java
  backend/emm-sale/src/test/java/com/emmsale/notification/application/UpdateNotificationQueryServiceTest.java
  backend/emm-sale/src/test/java/com/emmsale/notification/application/generator/MessageNotificationMessageGeneratorTest.java
  backend/emm-sale/src/test/java/com/emmsale/report/application/ReportCommandServiceTest.java
  backend/emm-sale/src/test/java/com/emmsale/report/application/ReportQueryServiceTest.java
  backend/emm-sale/src/test/resources/data-test.sql
Labels: 백엔드, 기능 추가, Low Priority

#553 Feature/#526 이미지를 db에 저장 및 삭제하는 기능
  backend/emm-sale/src/main/java/com/emmsale/image/application/ImageCommandService.java
  backend/emm-sale/src/main/java/com/emmsale/image/application/S3Client.java
  backend/emm-sale/src/main/java/com/emmsale/image/domain/Image.java
  backend/emm-sale/src/main/java/com/emmsale/image/domain/ImageType.java
  backend/emm-sale/src/main/java/com/emmsale/image/domain/repository/ImageRepository.java
  backend/emm-sale/src/main/java/com/emmsale/image/exception/ImageExceptionType.java
  backend/emm-sale/src/main/resources/data.sql
  backend/emm-sale/src/main/resources/schema.sql
  backend/emm-sale/src/test/java/com/emmsale/image/application/ImageCommandServiceTest.java
  backend/emm-sale/src/test/java/com/emmsale/image/domain/ImageTypeTest.java
  backend/emm-sale/src/test/resources/data-test.sql
Labels: 백엔드, 기능 추가, High Priority

#556 Feature/#535 행사 상세화면 상세정보 탭 구현
  android/2023-emmsale/app/proguard-rules.pro
  android/2023-emmsale/app/src/main/java/com/emmsale/data/mapper/EventDetailMapper.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/model/EventDetail.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/repository/concretes/DefaultRecruitmentRepository.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/repository/concretes/DefaultScrappedEventRepository.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/repository/interfaces/ScrappedEventRepository.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/service/ScrappedEventService.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/FetchResultUiState.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/bindingadapter/ChipGroupBindingAdapter.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/bindingadapter/LocalDateTimeBindingAdapter.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/views/ActivityTagChip.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/views/CancelablePrimaryTagChip.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/views/CategoryTagChip.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/views/EventTagChip.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/views/FilterTagChip.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/commentList/CommentFragment.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/competitionList/recyclerView/CompetitionViewHolder.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/conferenceList/recyclerView/ConferenceViewHolder.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventDetail/EventDetailActivity.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventDetail/EventDetailFragmentStateAdapter.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventDetail/EventDetailViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventDetail/EventTag.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventDetail/uiState/EventDetailUiState.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventDetailInfo/EventInfoFragment.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventDetailInfo/EventInfoViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/myProfile/MyProfileFragment.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/profile/ProfileActivity.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/recruitmentList/EventRecruitmentFragment.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/scrappedEventList/ScrappedEventViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/scrappedEventList/recyclerView/ScrappedEventViewHolder.kt
  android/2023-emmsale/app/src/main/res/drawable/bg_shadow.xml
  android/2023-emmsale/app/src/main/res/layout/activity_event_detail.xml
  android/2023-emmsale/app/src/main/res/layout/fragment_event_information.xml
  android/2023-emmsale/app/src/main/res/layout/item_conference.xml
  android/2023-emmsale/app/src/main/res/values/date_time_patterns.xml
  android/2023-emmsale/app/src/main/res/values/strings.xml
  android/2023-emmsale/app/src/test/java/com/emmsale/presentation/ui/eventdetail/EventDetailViewModelTest.kt
  android/2023-emmsale/app/src/test/java/com/emmsale/presentation/ui/eventdetail/information/EventInfoViewModelTest.kt
Labels: Android

#561 feat : 쪽지함 목록 조회 시 상대방 프로필 이미지 URL 반환
  backend/emm-sale/src/documentTest/java/com/emmsale/RoomApiTest.java
  backend/emm-sale/src/main/java/com/emmsale/message_room/application/dto/RoomResponse.java
Labels: 백엔드, 기능 추가, High Priority

#565 CommentApi의 findAll 메서드에 잘못 추가된 @RequestBody 제거
  backend/emm-sale/src/documentTest/java/com/emmsale/CommentApiTest.java
  backend/emm-sale/src/main/java/com/emmsale/comment/api/CommentApi.java
Labels: 버그, 백엔드

#566 Feature/#551 행사에 유료 온라인 여부 추가
  backend/emm-sale/src/documentTest/java/com/emmsale/EventApiTest.java
  backend/emm-sale/src/main/java/com/emmsale/activity/api/ActivityApi.java
  backend/emm-sale/src/main/java/com/emmsale/event/application/EventService.java
  backend/emm-sale/src/main/java/com/emmsale/event/application/dto/EventDetailRequest.java
  backend/emm-sale/src/main/java/com/emmsale/event/application/dto/EventResponse.java
  backend/emm-sale/src/main/java/com/emmsale/event/domain/Event.java
  backend/emm-sale/src/main/java/com/emmsale/event/domain/EventMode.java
  backend/emm-sale/src/main/java/com/emmsale/event/domain/PaymentType.java
  backend/emm-sale/src/main/resources/data.sql
  backend/emm-sale/src/main/resources/schema.sql
  backend/emm-sale/src/test/java/com/emmsale/comment/application/CommentCommandServiceTest.java
  backend/emm-sale/src/test/java/com/emmsale/event/EventFixture.java
  backend/emm-sale/src/test/java/com/emmsale/event/application/EventServiceTest.java
  backend/emm-sale/src/test/java/com/emmsale/event/domain/EventTest.java
Labels: 백엔드, 기능 추가

#576 Feature/#571 피드 반환 값 변경
  backend/emm-sale/src/documentTest/java/com/emmsale/FeedApiTest.java
  backend/emm-sale/src/main/java/com/emmsale/feed/application/FeedQueryService.java
  backend/emm-sale/src/main/java/com/emmsale/feed/application/dto/FeedDetailResponse.java
  backend/emm-sale/src/main/java/com/emmsale/feed/application/dto/FeedSimpleResponse.java
  backend/emm-sale/src/test/java/com/emmsale/feed/application/FeedQueryServiceTest.java
Labels: 백엔드, High Priority

#577 Feature/#574 scrap 반환값 변경
  backend/emm-sale/src/documentTest/java/com/emmsale/ScrapApiTest.java
  backend/emm-sale/src/main/java/com/emmsale/scrap/api/ScrapApi.java
  backend/emm-sale/src/main/java/com/emmsale/scrap/application/ScrapQueryService.java
  backend/emm-sale/src/test/java/com/emmsale/scrap/application/ScrapQueryServiceTest.java
Labels: 백엔드, 기능 추가

#580 Feature/#559 행사에 여러 개 이미지 등록 기능 구현
  backend/emm-sale/src/documentTest/asciidoc/index.adoc
  backend/emm-sale/src/documentTest/java/com/emmsale/EventApiTest.java
  backend/emm-sale/src/main/java/com/emmsale/GlobalControllerAdvice.java
  backend/emm-sale/src/main/java/com/emmsale/event/api/EventApi.java
  backend/emm-sale/src/main/java/com/emmsale/event/application/EventService.java
  backend/emm-sale/src/main/java/com/emmsale/event/application/dto/EventDetailRequest.java
  backend/emm-sale/src/main/java/com/emmsale/event/application/dto/EventDetailResponse.java
  backend/emm-sale/src/test/java/com/emmsale/event/application/EventServiceTest.java
  backend/emm-sale/src/test/java/com/emmsale/event/application/dto/EventDetailResponseTest.java
  backend/emm-sale/src/test/java/com/emmsale/helper/ServiceIntegrationTestHelper.java
Labels: 백엔드, 기능 추가, High Priority

#584 Feature/#552 차단한 사용자 피드 숨기기
  backend/emm-sale/src/documentTest/java/com/emmsale/FeedApiTest.java
  backend/emm-sale/src/main/java/com/emmsale/feed/api/FeedApi.java
  backend/emm-sale/src/main/java/com/emmsale/feed/application/FeedQueryService.java
  backend/emm-sale/src/main/java/com/emmsale/feed/domain/Feed.java
  backend/emm-sale/src/main/java/com/emmsale/feed/exception/FeedExceptionType.java
  backend/emm-sale/src/test/java/com/emmsale/feed/application/FeedQueryServiceTest.java
Labels: 백엔드, 기능 추가, Low Priority

#589 Feature/#588 메시지 보낼 때 반환값에 room id 추가
  backend/emm-sale/src/documentTest/asciidoc/index.adoc
  backend/emm-sale/src/documentTest/java/com/emmsale/MessagesApiTest.java
  backend/emm-sale/src/main/java/com/emmsale/message_room/api/MessagesApi.java
  backend/emm-sale/src/main/java/com/emmsale/message_room/application/MessageCommandService.java
  backend/emm-sale/src/main/java/com/emmsale/message_room/application/dto/MessageSendResponse.java
Labels: 백엔드, 기능 추가

#594 Feature/#585 쪽지 푸시 알림
  android/2023-emmsale/app/src/main/AndroidManifest.xml
  android/2023-emmsale/app/src/main/java/com/emmsale/data/model/Config.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/repository/concretes/DefaultConfigRepository.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/repository/interfaces/ConfigRepository.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/KerdyApplication.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/extension/ContextExt.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/extension/StringExt.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/service/KerdyFirebaseMessagingService.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/messageList/MessageListActivity.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/messageList/MessageListViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/messageRoomList/MessageRoomFragment.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/notificationConfig/NotificationConfigActivity.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/notificationConfig/NotificationConfigViewModel.kt
  android/2023-emmsale/app/src/main/res/layout/activity_notification_config.xml
  android/2023-emmsale/app/src/main/res/values/colors.xml
  android/2023-emmsale/app/src/main/res/values/ids.xml
  android/2023-emmsale/app/src/main/res/values/strings.xml
Labels: Android, Low Priority

#591 Feature/#587 피드 생성 일시 및 이미지 url 추가
  backend/emm-sale/src/documentTest/java/com/emmsale/FeedApiTest.java
  backend/emm-sale/src/main/java/com/emmsale/feed/application/FeedQueryService.java
  backend/emm-sale/src/main/java/com/emmsale/feed/application/dto/FeedDetailResponse.java
  backend/emm-sale/src/main/java/com/emmsale/feed/application/dto/FeedSimpleResponse.java
  backend/emm-sale/src/main/java/com/emmsale/image/domain/repository/ImageRepository.java
  backend/emm-sale/src/test/java/com/emmsale/feed/application/FeedQueryServiceTest.java
  backend/emm-sale/src/test/java/com/emmsale/image/domain/repository/ImageRepositoryTest.java
Labels: 백엔드, 기능 추가, High Priority

#595 feat: 스플래시에서 앱 버전 체크하도록 변경
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/splash/SplashActivity.kt
Labels: Android

#598 feat: 알림 보관함의 함께해요 요청 Fragment를 제거
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/notificationPageList/NotificationBoxActivity.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/notificationPageList/NotificationBoxFragmentStateAdapter.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/recruitmentNotificationList/RecruitmentNotificationFragment.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/recruitmentNotificationList/RecruitmentNotificationViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/recruitmentNotificationList/body/RecruitmentNotificationBodyAdapter.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/recruitmentNotificationList/body/RecruitmentNotificationBodyClickListener.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/recruitmentNotificationList/body/RecruitmentNotificationBodyDiffUtil.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/recruitmentNotificationList/body/RecruitmentNotificationBodyViewHolder.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/recruitmentNotificationList/dialog/RecruitmentAcceptedDialog.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/recruitmentNotificationList/dialog/RecruitmentRejectConfirmDialog.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/recruitmentNotificationList/header/RecruitmentNotificationHeaderAdapter.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/recruitmentNotificationList/header/RecruitmentNotificationHeaderClickListener.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/recruitmentNotificationList/header/RecruitmentNotificationHeaderDiffUtil.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/recruitmentNotificationList/header/RecruitmentNotificationHeaderViewHolder.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/recruitmentNotificationList/uiState/RecruitmentNotificationBodyUiState.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/recruitmentNotificationList/uiState/RecruitmentNotificationHeaderUiState.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/recruitmentNotificationList/uiState/RecruitmentNotificationMemberUiState.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/recruitmentNotificationList/uiState/RecruitmentNotificationStatusUiState.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/recruitmentNotificationList/uiState/RecruitmentNotificationUiEvent.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/recruitmentNotificationList/uiState/RecruitmentNotificationUiState.kt
  android/2023-emmsale/app/src/main/res/layout/activity_notification_box.xml
  android/2023-emmsale/app/src/main/res/layout/fragment_recruitment_notification.xml
  android/2023-emmsale/app/src/main/res/layout/item_recent_notification_header.xml
  android/2023-emmsale/app/src/main/res/layout/item_recruitment_notification_body.xml
  android/2023-emmsale/app/src/main/res/layout/item_recruitment_notification_header.xml
Labels: Android

#593 Feature/#583 이벤트 반환값에 행사기관 정보 추가
  backend/emm-sale/src/documentTest/java/com/emmsale/EventApiTest.java
  backend/emm-sale/src/main/java/com/emmsale/event/application/dto/EventDetailRequest.java
  backend/emm-sale/src/main/java/com/emmsale/event/domain/Event.java
  backend/emm-sale/src/main/resources/data.sql
  backend/emm-sale/src/main/resources/schema.sql
  backend/emm-sale/src/test/java/com/emmsale/comment/application/CommentCommandServiceTest.java
  backend/emm-sale/src/test/java/com/emmsale/event/EventFixture.java
  backend/emm-sale/src/test/java/com/emmsale/event/application/EventServiceTest.java
  backend/emm-sale/src/test/java/com/emmsale/event/domain/EventTest.java
Labels: 백엔드, 기능 추가, High Priority

#604 Feature/#599 쪽지를 실시간 채팅처럼 보이도록 변경
  android/2023-emmsale/app/src/main/AndroidManifest.xml
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/extension/ContextExt.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/service/KerdyFirebaseMessagingService.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/messageList/MessageListActivity.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/messageList/MessageListViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/messageList/recyclerview/MessageListAdapter.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/messageList/recyclerview/viewholder/OtherMessageViewHolder.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/messageList/uistate/MessageListUiEvent.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/messageList/uistate/MessagesUiState.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/messageList/uistate/OtherMessageUiState.kt
  android/2023-emmsale/app/src/main/res/drawable/bg_messagelist_new_message.xml
  android/2023-emmsale/app/src/main/res/layout/activity_message_list.xml
  android/2023-emmsale/app/src/main/res/layout/item_other_message.xml
  android/2023-emmsale/app/src/main/res/menu/menu_message_toolbar.xml
  android/2023-emmsale/app/src/main/res/values/strings.xml
Labels: Android

#609 feat: 행사 상세조회 이벤트 반환값에 행사정보 추가
  backend/emm-sale/src/documentTest/java/com/emmsale/EventApiTest.java
  backend/emm-sale/src/main/java/com/emmsale/event/application/dto/EventDetailResponse.java
  backend/emm-sale/src/test/java/com/emmsale/event/application/dto/EventDetailResponseTest.java
Labels: 백엔드, 기능 추가, High Priority

#612 Feature/#607 함께해요에서 쪽지 보내기
  android/2023-emmsale/app/src/main/java/com/emmsale/data/apiModel/response/EventResponse.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/mapper/EventDetailMapper.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/recruitmentDetail/RecruitmentPostDetailActivity.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/recruitmentDetail/RecruitmentPostDetailViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/recruitmentDetail/RequestCompanionFragmentDialog.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/recruitmentDetail/SendMessageDialog.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/recruitmentDetail/uiState/RecruitmentPostDetailUiEvent.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/recruitmentList/uiState/RecruitmentPostUiState.kt
  android/2023-emmsale/app/src/main/res/layout/activity_recruitment_post_detail.xml
  android/2023-emmsale/app/src/main/res/layout/dialog_recruitmentpostdetail_send_message.xml
  android/2023-emmsale/app/src/main/res/values/strings.xml
Labels: Android, 기능 추가, High Priority

#614 Fix/#613 태그 알림 설정 화면 수정
  android/2023-emmsale/app/src/main/java/com/emmsale/data/repository/concretes/DefaultEventTagRepository.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/notificationTagConfig/NotificationTagConfigViewModel.kt
Labels: 버그, Android, High Priority

#617 Fix/#615 로그아웃 해도 알림 오는 버그 수정
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/service/KerdyFirebaseMessagingService.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/feedDetail/uiState/CommentUiState.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/feedDetail/uiState/FeedDetailUiState.kt
  android/2023-emmsale/app/src/main/res/layout/item_all_comment.xml
  android/2023-emmsale/app/src/main/res/layout/item_all_deleted_comment.xml
  android/2023-emmsale/app/src/main/res/layout/item_feeddetail_feed_detail.xml
Labels: 버그, Android, High Priority

#620 Fix/#618 알림 api 수정
  android/2023-emmsale/app/src/main/AndroidManifest.xml
  android/2023-emmsale/app/src/main/java/com/emmsale/data/apiModel/response/NotificationResponse.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/mapper/UpdatedNotificationMapper.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/model/updatedNotification/ChildCommentNotification.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/service/KerdyFirebaseMessagingService.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/commentList/CommentFragment.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/competitionList/CompetitionFragment.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/conferenceList/ConferenceFragment.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventDetail/EventDetailActivity.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventDetail/EventDetailFragmentStateAdapter.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventDetail/EventDetailViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventDetailInfo/EventInfoFragment.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/feedDetail/FeedDetailActivity.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/primaryNotificationList/PrimaryNotificationFragment.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/primaryNotificationList/uiState/ChildCommentNotificationUiState.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/recruitmentDetail/RecruitmentPostDetailActivity.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/recruitmentList/EventRecruitmentFragment.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/scrappedEventList/ScrappedEventFragment.kt
  android/2023-emmsale/app/src/main/res/layout/activity_event_detail.xml
  android/2023-emmsale/app/src/main/res/layout/activity_feed_detail.xml
  android/2023-emmsale/app/src/main/res/layout/fragment_event_information.xml
  android/2023-emmsale/app/src/main/res/values/strings.xml
Labels: 버그, Android, High Priority

#623 Feature/#621 access 토큰 저장하지 못하는 버그
  android/2023-emmsale/app/build.gradle.kts
  android/2023-emmsale/app/proguard-glide.pro
  android/2023-emmsale/app/proguard-retrofit.pro
  android/2023-emmsale/app/proguard-rules.pro
  android/2023-emmsale/app/src/main/AndroidManifest.xml
  android/2023-emmsale/app/src/main/java/com/emmsale/data/common/ApiResult.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/common/AuthInterceptor.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/common/ImagePrefixUrl.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/mapper/FeedMapper.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/mapper/PostMapper.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/repository/concretes/DefaultConfigRepository.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/di/modules/repository/RepositoryModule.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/messageList/MessageListActivity.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/messageList/MessageListViewModel.kt
Labels: 버그, Android

#628 fix: 알림 보관함에서 스크롤시 팅기는 버그 수정
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/notificationPageList/NotificationBoxFragmentStateAdapter.kt
Labels: 버그, Android

#631 fix(SplashActivity): 안드로이드 API 버전 31 미만인 기기에서 스플래시 화면 보여줄 때 앱이 터지는 버그 수정
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/splash/SplashActivity.kt
Labels: 버그, Android, High Priority

#634 Feature/#633 행사 추가 api 요청 명세 변경
  backend/emm-sale/src/documentTest/asciidoc/index.adoc
  backend/emm-sale/src/documentTest/java/com/emmsale/EventApiTest.java
  backend/emm-sale/src/main/java/com/emmsale/event/api/EventApi.java
  backend/emm-sale/src/main/java/com/emmsale/event/application/EventService.java
  backend/emm-sale/src/main/java/com/emmsale/event/application/dto/EventDetailRequest.java
  backend/emm-sale/src/main/java/com/emmsale/image/domain/ImageType.java
  backend/emm-sale/src/main/java/com/emmsale/member/domain/InterestTagRepository.java
  backend/emm-sale/src/test/java/com/emmsale/event/application/EventServiceTest.java
  backend/emm-sale/src/test/java/com/emmsale/image/application/ImageCommandServiceTest.java
  backend/emm-sale/src/test/java/com/emmsale/image/domain/ImageTypeTest.java
Labels: 백엔드, 기능 추가, Low Priority

#642 Feature/#641 행사 수정 삭제 api에 이미지 처리 로직 추가
  backend/emm-sale/src/main/java/com/emmsale/event/application/EventService.java
Labels: 백엔드, 기능 추가, High Priority

#653 fix: 채팅창 진입 시 맨 하단으로 이동하지 않는 버그 수정
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/messageList/MessageListActivity.kt
Labels: Android, Low Priority

#654 Fix/#640 알림이 쌓이지 않는 버그
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/service/KerdyFirebaseMessagingService.kt
  android/2023-emmsale/app/src/main/res/layout/activity_message_list.xml
Labels: Android

#656 fix: 채팅 EditText 클릭시 키보드가 화면을 가리는 버그 수정
  android/2023-emmsale/app/src/main/AndroidManifest.xml
Labels: 버그, Android

#669 fix: 날짜 필터만 설정했을 때 필터 화면을 보여주지 않는 버그 수정
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/competitionList/CompetitionFragment.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/competitionList/uiState/CompetitionSelectedFilteringUiState.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/conferenceList/ConferenceFragment.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/conferenceList/ConferenceViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/conferenceList/uiState/ConferenceSelectedFilteringUiState.kt
  android/2023-emmsale/app/src/main/res/layout/fragment_competition.xml
  android/2023-emmsale/app/src/main/res/layout/fragment_conference.xml
Labels: 버그, Android, High Priority

#668 fix: 채팅 날짜 구분이 동일한 버그 수정
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/messageList/MessageListViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/messageList/uistate/MessageDateUiState.kt
Labels: Android

#671 Feature/#666 알림 스펙 변경
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/KerdyApplication.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/service/KerdyFirebaseMessagingService.kt
  android/2023-emmsale/app/src/main/res/values/ids.xml
  android/2023-emmsale/app/src/main/res/values/strings.xml
Labels: Android, 기능 추가, High Priority

#661 Fix/#646 쪽지 보내기 빈 문자열 보내는 버그 수정
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/profile/ProfileViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/profile/SendMessageDialog.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/recruitmentDetail/SendMessageDialog.kt
  android/2023-emmsale/app/src/main/res/layout/dialog_recruitmentpostdetail_send_message.xml
  android/2023-emmsale/app/src/main/res/layout/dialog_send_message.xml
Labels: 버그, Android, Low Priority

#672 Refactor/#649 댓글 행사 알림 스펙 변경
  backend/emm-sale/src/main/java/com/emmsale/event_publisher/CommentNotificationEvent.java
  backend/emm-sale/src/main/java/com/emmsale/event_publisher/EventNotificationEvent.java
  backend/emm-sale/src/main/java/com/emmsale/event_publisher/EventPublisher.java
  backend/emm-sale/src/main/java/com/emmsale/notification/application/FirebaseCloudMessageClient.java
  backend/emm-sale/src/main/java/com/emmsale/notification/application/NotificationEventListener.java
  backend/emm-sale/src/main/java/com/emmsale/notification/application/dto/CommentNotificationMessage.java
  backend/emm-sale/src/main/java/com/emmsale/notification/application/dto/EventNotificationMessage.java
  backend/emm-sale/src/main/java/com/emmsale/notification/application/generator/CommentNotificationMessageGenerator.java
  backend/emm-sale/src/main/java/com/emmsale/notification/application/generator/EventNotificationMessageGenerator.java
  backend/emm-sale/src/main/java/com/emmsale/notification/domain/Notification.java
  backend/emm-sale/src/main/java/com/emmsale/notification/domain/NotificationRepository.java
  backend/emm-sale/src/main/java/com/emmsale/notification/domain/NotificationType.java
  backend/emm-sale/src/main/resources/schema.sql
  backend/emm-sale/src/test/java/com/emmsale/comment/application/CommentCommandServiceEventIntegrationTest.java
  backend/emm-sale/src/test/java/com/emmsale/event_publisher/EventPublisherTest.java
  backend/emm-sale/src/test/java/com/emmsale/notification/application/NotificationEventListenerTest.java
  backend/emm-sale/src/test/resources/data-test.sql
Labels: 백엔드, 리팩터링
