Repository woowacourse-teams/2023-emmsale, pull requests merged in 2023-07, with the labels that each got.

#14 Feature/#3 이슈 및 pr 템플릿 적용
  .github/ISSUE_TEMPLATE/bug-report-template.md
  .github/ISSUE_TEMPLATE/etc-template.md
  .github/ISSUE_TEMPLATE/feature-template.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: GitHub

#17 feat : 도메인 및 엔티티 설계
  backend/emm-sale/src/main/java/com/emmsale/BaseEntity.java
  backend/emm-sale/src/main/java/com/emmsale/config/JpaAuditingConfig.java
  backend/emm-sale/src/main/java/com/emmsale/member/domain/Member.java
  backend/emm-sale/src/main/java/com/emmsale/price_history/domain/PriceHistory.java
  backend/emm-sale/src/main/java/com/emmsale/product/domain/PriceTrack.java
  backend/emm-sale/src/main/java/com/emmsale/product/domain/Product.java
  backend/emm-sale/src/main/java/com/emmsale/product/domain/PurchaseTemperature.java
  backend/emm-sale/src/main/java/com/emmsale/wish/domain/Wish.java
  backend/emm-sale/src/main/resources/application.properties
  backend/emm-sale/src/main/resources/application.yml
  backend/emm-sale/src/main/resources/schema.sql
Labels: 백엔드, 기능 추가

#43 Feature/#42 저장된 활동들을 전체 조회
  backend/emm-sale/src/main/java/com/emmsale/career/api/CareerApi.java
  backend/emm-sale/src/main/java/com/emmsale/career/application/CareerService.java
  backend/emm-sale/src/main/java/com/emmsale/career/application/dto/ActivityResponse.java
  backend/emm-sale/src/main/java/com/emmsale/career/application/dto/CareerResponse.java
  backend/emm-sale/src/main/java/com/emmsale/career/domain/ActivityType.java
  backend/emm-sale/src/main/java/com/emmsale/career/domain/Career.java
  backend/emm-sale/src/main/java/com/emmsale/career/domain/CareerRepository.java
  backend/emm-sale/src/main/resources/application.yml
  backend/emm-sale/src/main/resources/data.sql
  backend/emm-sale/src/main/resources/http/careers.http
  backend/emm-sale/src/main/resources/schema.sql
  backend/emm-sale/src/test/java/com/emmsale/career/api/CareerApiTest.java
  backend/emm-sale/src/test/java/com/emmsale/career/application/CareerServiceTest.java
Labels: 백엔드, 기능 추가

#47 Feature/#44 처음 가입한 사용자 정보 저장
  backend/emm-sale/src/main/java/com/emmsale/config/ArgumentResolverConfig.java
  backend/emm-sale/src/main/java/com/emmsale/member/api/MemberApi.java
  backend/emm-sale/src/main/java/com/emmsale/member/application/MemberCareerService.java
  backend/emm-sale/src/main/java/com/emmsale/member/application/MemberQueryService.java
  backend/emm-sale/src/main/java/com/emmsale/member/application/dto/MemberCareerInitialRequest.java
  backend/emm-sale/src/main/java/com/emmsale/member/domain/Member.java
  backend/emm-sale/src/main/java/com/emmsale/member/domain/MemberCareer.java
  backend/emm-sale/src/main/java/com/emmsale/member/domain/MemberCareerRepository.java
  backend/emm-sale/src/main/java/com/emmsale/member/domain/MemberRepository.java
  backend/emm-sale/src/main/java/com/emmsale/resolver/MemberArgumentResolver.java
  backend/emm-sale/src/main/resources/http/member.http
  backend/emm-sale/src/test/java/com/emmsale/EmmSaleApplicationTests.java
  backend/emm-sale/src/test/java/com/emmsale/career/api/CareerApiTest.java
  backend/emm-sale/src/test/java/com/emmsale/career/application/CareerServiceTest.java
  backend/emm-sale/src/test/java/com/emmsale/helper/MockMvcTestHelper.java
  backend/emm-sale/src/test/java/com/emmsale/helper/ServiceIntegrationTestHelper.java
  backend/emm-sale/src/test/java/com/emmsale/member/api/MemberApiTest.java
  backend/emm-sale/src/test/java/com/emmsale/member/application/MemberCareerServiceTest.java
Labels: 백엔드, 기능 추가

#36 Feature/#30-RestDocs_셋팅
  backend/emm-sale/build.gradle
  backend/emm-sale/src/docs/asciidoc/index.adoc
  backend/emm-sale/src/main/resources/static/docs/index.html
  backend/emm-sale/src/test/java/com/emmsale/restdocs/product/ProductController.java
  backend/emm-sale/src/test/java/com/emmsale/restdocs/product/ProductDocumentTest.java
  backend/emm-sale/src/test/java/com/emmsale/restdocs/product/ProductResponse.java
Labels: 백엔드, 기능 추가

#57 Feature/#37 자동배포 구현
  .github/workflows/backend-deploy.yml
Labels: 기능 추가, GitHub

#60 backend-main으로 보내는 PR이 있을 때 새로 빌드를 실행하는 스크립트 추가
  .github/workflows/backend-test.yml
Labels: 백엔드, GitHub

#61 빌드 하기전 backend-main으로 체크아웃하는 기능 추가
  .github/workflows/backend-test.yml
Labels: 백엔드, GitHub

#59 chore: android CI 구축
  .github/workflows/android-integration.yml
  android/2023-emmsale/app/src/androidTest/java/com/emmsale/ExampleInstrumentedTest.kt
  android/2023-emmsale/app/src/test/java/com/emmsale/ExampleUnitTest.kt
Labels: 환경 설정

#67 Feature/#66 기존 구현 api exception 처리 및 문서화
  backend/emm-sale/src/docs/asciidoc/index.adoc
  backend/emm-sale/src/main/java/com/emmsale/member/api/MemberApi.java
  backend/emm-sale/src/main/java/com/emmsale/member/application/MemberCareerService.java
  backend/emm-sale/src/main/java/com/emmsale/member/application/dto/MemberActivityResponse.java
  backend/emm-sale/src/main/java/com/emmsale/member/application/dto/MemberCareerAddRequest.java
  backend/emm-sale/src/main/java/com/emmsale/member/application/dto/MemberCareerDeleteRequest.java
  backend/emm-sale/src/main/java/com/emmsale/member/application/dto/MemberCareerResponse.java
  backend/emm-sale/src/main/java/com/emmsale/member/domain/MemberCareerRepository.java
  backend/emm-sale/src/main/java/com/emmsale/member/exception/MemberExceptionType.java
  backend/emm-sale/src/main/resources/http/member.http
  backend/emm-sale/src/main/resources/static/docs/index.html
  backend/emm-sale/src/test/java/com/emmsale/career/api/CareerApiTest.java
  backend/emm-sale/src/test/java/com/emmsale/career/application/CareerServiceTest.java
  backend/emm-sale/src/test/java/com/emmsale/member/api/MemberApiTest.java
  backend/emm-sale/src/test/java/com/emmsale/member/application/MemberCareerServiceTest.java
  backend/emm-sale/src/test/java/com/emmsale/member/domain/MemberCareerRepositoryTest.java
Labels: 백엔드, 기능 추가

#73 Feature/#68 배포 스크립트를 슬랙 앱과 연동
  .github/workflows/backend-deploy.yml
  .github/workflows/backend-dev-deploy.yml
Labels: 기능 추가, GitHub

#89 fix: career -> activity로 변경
  backend/emm-sale/src/docs/asciidoc/index.adoc
  backend/emm-sale/src/main/java/com/emmsale/member/api/MemberApi.java
  backend/emm-sale/src/test/java/com/emmsale/member/api/MemberApiTest.java
Labels: 버그, 백엔드

#91 Feature/#90 백엔드 배포 스크립트 수정
  .github/workflows/backend-dev-deploy.yml
  backend/emm-sale/src/main/java/com/emmsale/event/api/EventApi.java
  backend/emm-sale/src/main/java/com/emmsale/event/application/EventService.java
  backend/emm-sale/src/main/java/com/emmsale/event/application/dto/EventResponse.java
  backend/emm-sale/src/main/java/com/emmsale/event/domain/repository/EventRepository.java
  backend/emm-sale/src/test/java/com/emmsale/event/api/EventApiTest.java
Labels: 백엔드, GitHub, 환경 설정

#92 fix/#90 백엔드 배포 스크립트 수정
  .github/workflows/backend-dev-deploy.yml
Labels: 백엔드, GitHub, 환경 설정

#87 Feature/#81 로그인 사용자 프로필 이미지 추가 기능 구현
  backend/emm-sale/src/main/java/com/emmsale/login/application/LoginService.java
  backend/emm-sale/src/main/java/com/emmsale/login/application/dto/GithubProfileResponse.java
  backend/emm-sale/src/main/java/com/emmsale/login/utils/GithubClient.java
  backend/emm-sale/src/main/java/com/emmsale/member/domain/Member.java
  backend/emm-sale/src/test/java/com/emmsale/login/application/LoginServiceTest.java
  backend/emm-sale/src/test/java/com/emmsale/member/application/MemberQueryServiceTest.java
Labels: 백엔드, 기능 추가

#94 Feature/#85 컨퍼런스 상세 정보 조회 기능추가
  backend/emm-sale/src/docs/asciidoc/index.adoc
  backend/emm-sale/src/main/java/com/emmsale/event/api/EventApi.java
  backend/emm-sale/src/main/java/com/emmsale/event/application/EventService.java
  backend/emm-sale/src/main/java/com/emmsale/event/application/dto/EventDetailResponse.java
  backend/emm-sale/src/main/java/com/emmsale/event/application/dto/EventResponse.java
  backend/emm-sale/src/main/java/com/emmsale/event/domain/Event.java
  backend/emm-sale/src/main/java/com/emmsale/event/exception/EventException.java
  backend/emm-sale/src/main/java/com/emmsale/event/exception/EventExceptionType.java
  backend/emm-sale/src/main/resources/http/event.http
  backend/emm-sale/src/test/java/com/emmsale/event/EventFixture.java
  backend/emm-sale/src/test/java/com/emmsale/event/api/EventApiTest.java
  backend/emm-sale/src/test/java/com/emmsale/event/application/EventServiceTest.java
Labels: 백엔드, 기능 추가

#107 Feature/#104 로그인 http 메서드 수정 및 authorization extractor 예외 추가
  backend/emm-sale/src/main/java/com/emmsale/login/api/LoginApi.java
  backend/emm-sale/src/main/java/com/emmsale/login/exception/LoginExceptionType.java
  backend/emm-sale/src/main/java/com/emmsale/login/utils/AuthorizationExtractor.java
  backend/emm-sale/src/main/java/com/emmsale/resolver/MemberArgumentResolver.java
  backend/emm-sale/src/test/java/com/emmsale/login/api/LoginApiTest.java
Labels: 백엔드, 리팩터링, 기능 추가, Low Priority

#103 Feature/#45 깃허브 로그인 구현
  .DS_Store
  .idea/.gitignore
  .idea/2023-emmsale.iml
  .idea/modules.xml
  .idea/vcs.xml
  android/2023-emmsale/app/build.gradle.kts
  android/2023-emmsale/app/src/main/AndroidManifest.xml
  android/2023-emmsale/app/src/main/java/com/emmsale/MainActivity.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/common/ApiResult.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/common/RetrofitProvider.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/login/Login.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/login/LoginRepository.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/login/LoginRepositoryImpl.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/login/LoginService.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/login/dto/LoginApiModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/token/Token.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/token/TokenRepository.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/token/TokenRepositoryImpl.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/base/viewmodel/BaseViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/base/viewmodel/DispatcherProvider.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/base/viewmodel/DispatcherProviderImpl.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/base/viewmodel/LoadingUiState.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/login/LoginActivity.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/login/LoginViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/login/LoginViewModelFactory.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/login/uistate/LoginUiState.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/utils/binding/ViewDataBindingExt.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/utils/builder/UriBuilder.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/utils/extensions/ViewModelExt.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/utils/keys/Keys.kt
  android/2023-emmsale/app/src/main/res/drawable/bg_login_github.xml
  android/2023-emmsale/app/src/main/res/drawable/ic_login_github.xml
  android/2023-emmsale/app/src/main/res/drawable/img_login_logo.png
  android/2023-emmsale/app/src/main/res/layout/activity_login.xml
  android/2023-emmsale/app/src/main/res/values/colors.xml
  backend/.DS_Store
Labels: 안드로이드, High Priority

#97 Feature/#83 댓글 대댓글 crud api 구현
  backend/emm-sale/src/docs/asciidoc/index.adoc
  backend/emm-sale/src/main/java/com/emmsale/base/BaseEntity.java
  backend/emm-sale/src/main/java/com/emmsale/comment/api/CommentApi.java
  backend/emm-sale/src/main/java/com/emmsale/comment/application/CommentCommandService.java
  backend/emm-sale/src/main/java/com/emmsale/comment/application/CommentQueryService.java
  backend/emm-sale/src/main/java/com/emmsale/comment/application/dto/CommentAddRequest.java
  backend/emm-sale/src/main/java/com/emmsale/comment/application/dto/CommentHierarchyResponse.java
  backend/emm-sale/src/main/java/com/emmsale/comment/application/dto/CommentModifyRequest.java
  backend/emm-sale/src/main/java/com/emmsale/comment/application/dto/CommentResponse.java
  backend/emm-sale/src/main/java/com/emmsale/comment/domain/Comment.java
  backend/emm-sale/src/main/java/com/emmsale/comment/domain/CommentRepository.java
  backend/emm-sale/src/main/java/com/emmsale/comment/exception/CommentException.java
  backend/emm-sale/src/main/java/com/emmsale/comment/exception/CommentExceptionType.java
  backend/emm-sale/src/main/java/com/emmsale/member/domain/Member.java
  backend/emm-sale/src/main/resources/http/comment.http
  backend/emm-sale/src/main/resources/schema.sql
  backend/emm-sale/src/main/resources/static/docs/index.html
  backend/emm-sale/src/test/java/com/emmsale/comment/api/CommentApiTest.java
  backend/emm-sale/src/test/java/com/emmsale/comment/application/CommentCommandServiceTest.java
  backend/emm-sale/src/test/java/com/emmsale/comment/application/CommentQueryServiceTest.java
  backend/emm-sale/src/test/java/com/emmsale/comment/domain/CommentRepositoryTest.java
  backend/emm-sale/src/test/java/com/emmsale/member/domain/MemberActivityRepositoryTest.java
Labels: 백엔드, 기능 추가

#108 Feature/#86 컨퍼런스 목록 조회 api 구현
  backend/emm-sale/src/docs/asciidoc/index.adoc
  backend/emm-sale/src/main/java/com/emmsale/event/api/EventApi.java
  backend/emm-sale/src/main/java/com/emmsale/event/application/EventService.java
  backend/emm-sale/src/main/java/com/emmsale/event/application/dto/EventResponse.java
  backend/emm-sale/src/main/java/com/emmsale/event/domain/Event.java
  backend/emm-sale/src/main/java/com/emmsale/event/domain/EventStatus.java
  backend/emm-sale/src/main/java/com/emmsale/event/domain/EventTag.java
  backend/emm-sale/src/main/java/com/emmsale/event/domain/repository/EventTagRepository.java
  backend/emm-sale/src/main/java/com/emmsale/event/exception/EventExceptionType.java
  backend/emm-sale/src/main/java/com/emmsale/tag/domain/Tag.java
  backend/emm-sale/src/main/java/com/emmsale/tag/domain/TagRepository.java
  backend/emm-sale/src/main/java/com/emmsale/tag/exception/TagException.java
  backend/emm-sale/src/main/java/com/emmsale/tag/exception/TagExceptionType.java
  backend/emm-sale/src/main/resources/http/event.http
  backend/emm-sale/src/test/java/com/emmsale/event/EventFixture.java
  backend/emm-sale/src/test/java/com/emmsale/event/api/EventApiTest.java
  backend/emm-sale/src/test/java/com/emmsale/event/application/EventServiceTest.java
  backend/emm-sale/src/test/java/com/emmsale/member/api/MemberApiTest.java
  backend/emm-sale/src/test/java/com/emmsale/tag/TagFixture.java
Labels: 백엔드, 기능 추가, High Priority

#110 Feature/#100 오픈채팅 프로필 url 등록 기능 구현
  backend/emm-sale/src/docs/asciidoc/index.adoc
  backend/emm-sale/src/main/java/com/emmsale/member/api/MemberApi.java
  backend/emm-sale/src/main/java/com/emmsale/member/application/MemberUpdateService.java
  backend/emm-sale/src/main/java/com/emmsale/member/application/dto/OpenProfileUrlRequest.java
  backend/emm-sale/src/main/java/com/emmsale/member/domain/Member.java
  backend/emm-sale/src/main/resources/http/member.http
  backend/emm-sale/src/main/resources/static/docs/index.html
  backend/emm-sale/src/test/java/com/emmsale/member/MemberFixture.java
  backend/emm-sale/src/test/java/com/emmsale/member/api/MemberApiTest.java
  backend/emm-sale/src/test/java/com/emmsale/member/application/MemberUpdateServiceTest.java
Labels: 백엔드, 기능 추가, Low Priority

#117 fix: 반환할 때 태그도 받도록 수정
  backend/emm-sale/src/main/java/com/emmsale/event/application/dto/EventDetailResponse.java
  backend/emm-sale/src/main/java/com/emmsale/event/domain/Event.java
  backend/emm-sale/src/test/java/com/emmsale/event/api/EventApiTest.java
Labels: 버그, High Priority

#119 Feature/#112 컨퍼런스 참여자 목록 조회하기
  backend/emm-sale/src/docs/asciidoc/index.adoc
  backend/emm-sale/src/main/java/com/emmsale/event/api/EventApi.java
  backend/emm-sale/src/main/java/com/emmsale/event/application/EventService.java
  backend/emm-sale/src/main/java/com/emmsale/event/application/dto/ParticipantResponse.java
  backend/emm-sale/src/main/java/com/emmsale/event/domain/Event.java
  backend/emm-sale/src/main/resources/data.sql
  backend/emm-sale/src/main/resources/http/event.http
  backend/emm-sale/src/test/java/com/emmsale/event/api/EventApiTest.java
  backend/emm-sale/src/test/java/com/emmsale/event/application/EventServiceTest.java
Labels: 백엔드, 기능 추가, High Priority

#121 Feature/#105 fcm 푸시 알림
  .github/workflows/android-integration.yml
  android/2023-emmsale/app/build.gradle.kts
  android/2023-emmsale/app/src/main/AndroidManifest.xml
  android/2023-emmsale/app/src/main/java/com/emmsale/data/event/Event.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/event/EventRepository.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/event/EventRepositoryImpl.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/event/EventService.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/event/dto/EventApiModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/fcmToken/FcmToken.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/fcmToken/FcmTokenRepository.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/fcmToken/FcmTokenRepositoryImpl.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/fcmToken/FcmTokenService.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/fcmToken/dto/FcmTokenApiModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/token/TokenRepositoryImpl.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/di/RepositoryContainer.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/di/ServiceContainer.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/extension/AlertDialogExt.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/extension/ContextExt.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/notification/NotificationHelper.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/service/KerdyFirebaseMessagingService.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/login/LoginActivity.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/login/LoginViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/onboarding/OnboardingViewModel.kt
  android/2023-emmsale/app/src/main/res/values/strings.xml
Labels: 안드로이드

#125 career activity 변환 작업
  backend/emm-sale/src/docs/asciidoc/index.adoc
  backend/emm-sale/src/main/java/com/emmsale/activity/api/ActivityApi.java
  backend/emm-sale/src/main/java/com/emmsale/member/api/MemberApi.java
  backend/emm-sale/src/main/java/com/emmsale/member/application/MemberActivityService.java
  backend/emm-sale/src/main/java/com/emmsale/member/application/dto/MemberActivityResponses.java
  backend/emm-sale/src/main/java/com/emmsale/member/domain/MemberActivityRepository.java
  backend/emm-sale/src/main/java/com/emmsale/member/exception/MemberExceptionType.java
  backend/emm-sale/src/main/resources/http/member.http
  backend/emm-sale/src/test/java/com/emmsale/activity/api/ActivityApiTest.java
  backend/emm-sale/src/test/java/com/emmsale/activity/application/ActivityServiceTest.java
  backend/emm-sale/src/test/java/com/emmsale/member/api/MemberApiTest.java
  backend/emm-sale/src/test/java/com/emmsale/member/application/MemberActivityServiceTest.java
  backend/emm-sale/src/test/java/com/emmsale/member/domain/MemberActivityRepositoryTest.java
  backend/emm-sale/src/test/java/com/emmsale/restdocs/product/ProductController.java
  backend/emm-sale/src/test/java/com/emmsale/restdocs/product/ProductDocumentTest.java
  backend/emm-sale/src/test/java/com/emmsale/restdocs/product/ProductResponse.java
Labels: 백엔드, Low Priority

#127 Feature/#123 사용자의 프로필 조회 api 구현
  backend/emm-sale/src/docs/asciidoc/index.adoc
  backend/emm-sale/src/main/java/com/emmsale/member/api/MemberApi.java
  backend/emm-sale/src/main/java/com/emmsale/member/application/MemberQueryService.java
  backend/emm-sale/src/main/java/com/emmsale/member/application/dto/MemberProfileResponse.java
  backend/emm-sale/src/main/resources/data.sql
  backend/emm-sale/src/main/resources/http/member.http
  backend/emm-sale/src/test/java/com/emmsale/member/api/MemberApiTest.java
  backend/emm-sale/src/test/java/com/emmsale/member/application/MemberQueryServiceTest.java
Labels: 백엔드, 기능 추가, High Priority

#136 Feature/#134 로그인 rest docs 문서 생성
  backend/emm-sale/src/docs/asciidoc/index.adoc
  backend/emm-sale/src/main/resources/static/docs/index.html
  backend/emm-sale/src/test/java/com/emmsale/login/api/LoginApiTest.java
Labels: 문서, 백엔드, High Priority

#132 Feature/#99 알림 추가하기 api 구현
  backend/emm-sale/src/docs/asciidoc/index.adoc
  backend/emm-sale/src/main/java/com/emmsale/event/domain/repository/EventRepository.java
  backend/emm-sale/src/main/java/com/emmsale/member/domain/MemberRepository.java
  backend/emm-sale/src/main/java/com/emmsale/notification/api/NotificationApi.java
  backend/emm-sale/src/main/java/com/emmsale/notification/application/NotificationCommandService.java
  backend/emm-sale/src/main/java/com/emmsale/notification/application/NotificationQueryService.java
  backend/emm-sale/src/main/java/com/emmsale/notification/application/dto/FcmTokenRequest.java
  backend/emm-sale/src/main/java/com/emmsale/notification/application/dto/NotificationModifyRequest.java
  backend/emm-sale/src/main/java/com/emmsale/notification/application/dto/NotificationRequest.java
  backend/emm-sale/src/main/java/com/emmsale/notification/application/dto/NotificationResponse.java
  backend/emm-sale/src/main/java/com/emmsale/notification/domain/FcmToken.java
  backend/emm-sale/src/main/java/com/emmsale/notification/domain/FcmTokenRepository.java
  backend/emm-sale/src/main/java/com/emmsale/notification/domain/Notification.java
  backend/emm-sale/src/main/java/com/emmsale/notification/domain/NotificationRepository.java
  backend/emm-sale/src/main/java/com/emmsale/notification/domain/NotificationStatus.java
  backend/emm-sale/src/main/java/com/emmsale/notification/exception/NotificationException.java
  backend/emm-sale/src/main/java/com/emmsale/notification/exception/NotificationExceptionType.java
  backend/emm-sale/src/main/resources/data.sql
  backend/emm-sale/src/main/resources/http/notification.http
  backend/emm-sale/src/main/resources/schema.sql
  backend/emm-sale/src/main/resources/static/docs/index.html
  backend/emm-sale/src/test/java/com/emmsale/event/domain/repository/EventRepositoryTest.java
  backend/emm-sale/src/test/java/com/emmsale/member/domain/MemberRepositoryTest.java
  backend/emm-sale/src/test/java/com/emmsale/notification/api/NotificationApiTest.java
  backend/emm-sale/src/test/java/com/emmsale/notification/application/NotificationCommandServiceTest.java
Labels: 백엔드, 기능 추가

#131 fix: status로 필터링 시 발생하는 500 오류 해결
  backend/emm-sale/src/main/java/com/emmsale/event/application/EventService.java
  backend/emm-sale/src/main/java/com/emmsale/event/domain/EventStatus.java
  backend/emm-sale/src/test/java/com/emmsale/event/application/EventServiceTest.java
  backend/emm-sale/src/test/java/com/emmsale/event/domain/EventStatusTest.java
  backend/emm-sale/src/test/java/com/emmsale/event/domain/EventTest.java
Labels: 버그, 백엔드, High Priority

#137 Feature/#135 로그인 결과 반환값에 온보딩 여부 추가
  backend/emm-sale/src/main/java/com/emmsale/login/application/LoginService.java
  backend/emm-sale/src/main/java/com/emmsale/login/application/dto/GithubProfileResponse.java
  backend/emm-sale/src/main/java/com/emmsale/login/application/dto/MemberQueryResponse.java
  backend/emm-sale/src/main/java/com/emmsale/login/application/dto/TokenResponse.java
  backend/emm-sale/src/main/java/com/emmsale/member/application/MemberQueryService.java
  backend/emm-sale/src/main/java/com/emmsale/member/domain/Member.java
  backend/emm-sale/src/main/resources/schema.sql
  backend/emm-sale/src/test/java/com/emmsale/event/application/EventServiceTest.java
  backend/emm-sale/src/test/java/com/emmsale/event/domain/EventTest.java
  backend/emm-sale/src/test/java/com/emmsale/login/api/LoginApiTest.java
  backend/emm-sale/src/test/java/com/emmsale/member/MemberFixture.java
  backend/emm-sale/src/test/java/com/emmsale/member/application/MemberQueryServiceTest.java
Labels: 백엔드, 기능 추가, High Priority

#161 Feature/#133 fcm서버에 알림 정보 보내기
  .github/workflows/backend-dev-deploy.yml
  backend/emm-sale/build.gradle
  backend/emm-sale/src/main/java/com/emmsale/config/RestTemplateConfig.java
  backend/emm-sale/src/main/java/com/emmsale/login/utils/GithubClient.java
  backend/emm-sale/src/main/java/com/emmsale/notification/application/FirebaseCloudMessageClient.java
  backend/emm-sale/src/main/java/com/emmsale/notification/application/NotificationCommandService.java
  backend/emm-sale/src/main/java/com/emmsale/notification/application/NotificationQueryService.java
  backend/emm-sale/src/main/java/com/emmsale/notification/application/dto/FcmMessage.java
  backend/emm-sale/src/main/java/com/emmsale/notification/exception/NotificationExceptionType.java
  backend/emm-sale/src/main/resources/application.yml
  backend/emm-sale/src/main/resources/http/notification.http
  backend/emm-sale/src/test/java/com/emmsale/notification/application/NotificationCommandServiceTest.java
Labels: 백엔드, 기능 추가, High Priority

#168 fix : json 파일 읽히지 않는 것 수정
  .github/workflows/backend-dev-deploy.yml
Labels: 버그, GitHub, 환경 설정

#138 Feature/#115 이벤트 cud 기능 구현
  backend/emm-sale/src/docs/asciidoc/index.adoc
  backend/emm-sale/src/main/java/com/emmsale/GlobalControllerAdvice.java
  backend/emm-sale/src/main/java/com/emmsale/event/api/EventApi.java
  backend/emm-sale/src/main/java/com/emmsale/event/application/EventService.java
  backend/emm-sale/src/main/java/com/emmsale/event/application/dto/EventDetailRequest.java
  backend/emm-sale/src/main/java/com/emmsale/event/domain/Event.java
  backend/emm-sale/src/main/java/com/emmsale/event/domain/EventTag.java
  backend/emm-sale/src/main/java/com/emmsale/event/domain/repository/EventTagRepository.java
  backend/emm-sale/src/main/java/com/emmsale/event/exception/EventExceptionType.java
  backend/emm-sale/src/main/java/com/emmsale/notification/application/NotificationQueryService.java
  backend/emm-sale/src/main/java/com/emmsale/tag/application/dto/TagRequest.java
  backend/emm-sale/src/test/java/com/emmsale/event/api/EventApiTest.java
  backend/emm-sale/src/test/java/com/emmsale/event/application/EventServiceTest.java
  backend/emm-sale/src/test/java/com/emmsale/event/domain/EventTest.java
  backend/emm-sale/src/test/java/com/emmsale/event/domain/repository/EventRepositoryTest.java
Labels: 백엔드, 기능 추가, Low Priority
