Repository woowacourse-teams/2023-emmsale, pull requests merged in 2023-08, with the labels that each got.

#162 Feature/#141-알림 목록 조회 API 구현
  backend/emm-sale/src/docs/asciidoc/index.adoc
  backend/emm-sale/src/main/java/com/emmsale/notification/api/NotificationApi.java
  backend/emm-sale/src/main/java/com/emmsale/notification/application/NotificationCommandService.java
  backend/emm-sale/src/main/java/com/emmsale/notification/domain/NotificationRepository.java
  backend/emm-sale/src/main/resources/static/docs/index.html
  backend/emm-sale/src/test/java/com/emmsale/notification/api/NotificationApiTest.java
  backend/emm-sale/src/test/java/com/emmsale/notification/application/NotificationCommandServiceTest.java
  backend/emm-sale/src/test/resources/data-test.sql
Labels: 백엔드, 기능 추가, Low Priority

#166 Feature/#149 특정 사용자 Activity 조회 API 수정
  backend/emm-sale/src/main/java/com/emmsale/member/api/MemberApi.java
  backend/emm-sale/src/main/java/com/emmsale/member/application/MemberActivityService.java
  backend/emm-sale/src/main/resources/http/member.http
  backend/emm-sale/src/test/java/com/emmsale/member/api/MemberApiTest.java
Labels: 백엔드, Low Priority

#173 Feature/#170 이벤트 상세정보 조회 api
  backend/emm-sale/src/main/java/com/emmsale/event/api/EventApi.java
  backend/emm-sale/src/main/java/com/emmsale/event/application/EventService.java
  backend/emm-sale/src/main/java/com/emmsale/event/application/dto/EventDetailRequest.java
  backend/emm-sale/src/main/java/com/emmsale/event/application/dto/EventDetailResponse.java
  backend/emm-sale/src/main/java/com/emmsale/event/domain/Event.java
  backend/emm-sale/src/main/java/com/emmsale/event/domain/EventType.java
  backend/emm-sale/src/main/resources/data.sql
  backend/emm-sale/src/main/resources/schema.sql
  backend/emm-sale/src/test/java/com/emmsale/comment/application/CommentCommandServiceTest.java
  backend/emm-sale/src/test/java/com/emmsale/comment/application/CommentQueryServiceTest.java
  backend/emm-sale/src/test/java/com/emmsale/comment/domain/CommentRepositoryTest.java
  backend/emm-sale/src/test/java/com/emmsale/event/EventFixture.java
  backend/emm-sale/src/test/java/com/emmsale/event/api/EventApiTest.java
  backend/emm-sale/src/test/java/com/emmsale/event/application/EventServiceTest.java
  backend/emm-sale/src/test/java/com/emmsale/event/domain/EventTest.java
Labels: 백엔드, 기능 추가, High Priority

#165 Feature/#148 회원 탈퇴 api 구현
  backend/emm-sale/src/docs/asciidoc/index.adoc
  backend/emm-sale/src/main/java/com/emmsale/member/api/MemberApi.java
  backend/emm-sale/src/main/java/com/emmsale/member/application/MemberUpdateService.java
  backend/emm-sale/src/main/java/com/emmsale/member/exception/MemberExceptionType.java
  backend/emm-sale/src/main/resources/http/member.http
  backend/emm-sale/src/test/java/com/emmsale/member/api/MemberApiTest.java
  backend/emm-sale/src/test/java/com/emmsale/member/application/MemberUpdateServiceTest.java
Labels: 백엔드, 기능 추가, Low Priority

#174 Feature/#163 행사 목록 조회 시 반환 데이터에 필드 추가
  backend/emm-sale/src/main/java/com/emmsale/event/api/EventApi.java
  backend/emm-sale/src/main/java/com/emmsale/event/application/EventService.java
  backend/emm-sale/src/main/java/com/emmsale/event/application/dto/EventResponse.java
  backend/emm-sale/src/main/java/com/emmsale/event/domain/Event.java
  backend/emm-sale/src/main/java/com/emmsale/event/domain/repository/EventRepository.java
  backend/emm-sale/src/main/java/com/emmsale/event/exception/EventExceptionType.java
  backend/emm-sale/src/main/resources/http/event.http
  backend/emm-sale/src/main/resources/schema.sql
  backend/emm-sale/src/test/java/com/emmsale/event/EventFixture.java
  backend/emm-sale/src/test/java/com/emmsale/event/api/EventApiTest.java
  backend/emm-sale/src/test/java/com/emmsale/event/application/EventServiceTest.java
Labels: 백엔드, 기능 추가, High Priority

#176 Feature/#175 crashlytics 환경 구축
  android/2023-emmsale/app/build.gradle.kts
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/views/ActivityTag.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/views/EventTag.kt
  android/2023-emmsale/build.gradle.kts
Labels: 안드로이드, Low Priority

#139 Feature/#48 프로필 화면 구현
  android/2023-emmsale/app/build.gradle.kts
  android/2023-emmsale/app/src/main/AndroidManifest.xml
  android/2023-emmsale/app/src/main/java/com/emmsale/data/activity/Activity1.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/activity/ActivityType.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/member/Member1.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/member/MemberRepository.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/member/MemberRepositoryImpl.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/member/MemberService.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/member/dto/ActivitiesAssociatedByActivityTypeApiModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/member/dto/MemberWithoutActivitiesApiModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/member/mapper/MemberMapper.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/views/ActivityTag.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/views/EventTag.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/login/LoginActivity.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/MainActivity.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/events/EventsFragment.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/myProfile/MyProfileFragment.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/myProfile/MyProfileViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/myProfile/adapter/ActivitiesAdapter.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/myProfile/adapter/ActivityViewHolder.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/myProfile/adapter/JobsAdapter.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/myProfile/adapter/JobsViewHolder.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/myProfile/itemDecoration/ActivitiesAdapterDecoration.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/myProfile/uiState/ActivityUiState.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/myProfile/uiState/MyProfileScreenUiState.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/onboarding/OnboardingActivity.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/utils/bindingadapter/ImageViewBindingAdapter.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/utils/bindingadapter/SwipeRefreshLayoutBindingAdapter.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/utils/extension/IntExt.kt
  android/2023-emmsale/app/src/main/res/color/color_bottom_navigation_view_icon.xml
  android/2023-emmsale/app/src/main/res/drawable/bg_myprofile_activityicon.xml
  android/2023-emmsale/app/src/main/res/drawable/bg_myprofile_imagedecoration.xml
  android/2023-emmsale/app/src/main/res/drawable/bg_myprofile_job.xml
  android/2023-emmsale/app/src/main/res/drawable/ic_main_menuitemhome.xml
  android/2023-emmsale/app/src/main/res/drawable/ic_main_menuitemprofile.xml
  android/2023-emmsale/app/src/main/res/drawable/ic_main_menuitemsetting.xml
  android/2023-emmsale/app/src/main/res/drawable/ic_myprofile_activitylabeldecorator.xml
  android/2023-emmsale/app/src/main/res/drawable/ic_myprofile_activitynamedecorator.xml
  android/2023-emmsale/app/src/main/res/drawable/ic_myprofile_education.xml
  android/2023-emmsale/app/src/main/res/font/nanum_square.xml
  android/2023-emmsale/app/src/main/res/font/nanum_square_bold.ttf
  android/2023-emmsale/app/src/main/res/font/nanum_square_extra_bold.ttf
  android/2023-emmsale/app/src/main/res/font/nanum_square_regular.ttf
  android/2023-emmsale/app/src/main/res/layout/activity_main.xml
  android/2023-emmsale/app/src/main/res/layout/fragment_events.xml
  android/2023-emmsale/app/src/main/res/layout/fragment_my_profile.xml
  android/2023-emmsale/app/src/main/res/layout/item_myprofile_activities.xml
  android/2023-emmsale/app/src/main/res/layout/item_myprofile_jobs.xml
  android/2023-emmsale/app/src/main/res/menu/menu_main_bottomnavigationview.xml
  android/2023-emmsale/app/src/main/res/values/colors.xml
  android/2023-emmsale/app/src/main/res/values/strings.xml
  android/2023-emmsale/app/src/main/res/values/styles.xml
  android/2023-emmsale/app/src/main/res/values/themes.xml
  android/2023-emmsale/app/src/test/java/com/emmsale/data/member/MemberRepositoryImplTest.kt
  android/2023-emmsale/app/src/test/java/com/emmsale/data/member/MemberServiceTest.kt
Labels: 안드로이드, 기능 추가, High Priority

#181 feat : 부모 ID로 대댓글 조회하는 API 추가
  backend/emm-sale/src/docs/asciidoc/index.adoc
  backend/emm-sale/src/main/java/com/emmsale/comment/api/CommentApi.java
  backend/emm-sale/src/main/java/com/emmsale/comment/application/CommentQueryService.java
  backend/emm-sale/src/main/java/com/emmsale/comment/domain/CommentRepository.java
  backend/emm-sale/src/main/resources/http/comment.http
  backend/emm-sale/src/main/resources/static/docs/index.html
  backend/emm-sale/src/test/java/com/emmsale/comment/api/CommentApiTest.java
  backend/emm-sale/src/test/java/com/emmsale/comment/application/CommentQueryServiceTest.java
  backend/emm-sale/src/test/java/com/emmsale/comment/domain/CommentRepositoryTest.java
Labels: 백엔드, 기능 추가, High Priority

#183 Feature/#182 이미 참여한 이벤트인지 확인하는 기능 추가
  backend/emm-sale/src/docs/asciidoc/index.adoc
  backend/emm-sale/src/main/java/com/emmsale/event/api/EventApi.java
  backend/emm-sale/src/main/java/com/emmsale/event/application/EventService.java
  backend/emm-sale/src/main/java/com/emmsale/event/domain/repository/ParticipantRepository.java
  backend/emm-sale/src/main/resources/http/event.http
  backend/emm-sale/src/test/java/com/emmsale/event/api/EventApiTest.java
  backend/emm-sale/src/test/java/com/emmsale/event/application/EventServiceTest.java
  backend/emm-sale/src/test/java/com/emmsale/event/domain/repository/ParticipantRepositoryTest.java
Labels: 백엔드, 기능 추가, High Priority

#187 Feature/#177 production develop 서버 배포 자동화 스크립트 수정
  .github/workflows/backend-dev-deploy.yml
  .github/workflows/backend-prod-deploy.yml
  backend/emm-sale/Dockerfile-dev
Labels: 백엔드, 환경 설정, High Priority

#191 Feature/#111 행사 상세 화면 구현
  android/2023-emmsale/app/src/main/AndroidManifest.xml
  android/2023-emmsale/app/src/main/java/com/emmsale/data/eventdetail/EventDetail.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/eventdetail/EventDetailRepository.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/eventdetail/EventDetailRepositoryImpl.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/eventdetail/EventDetailService.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/eventdetail/dto/EventDetailApiModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/member/MemberService.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/di/RepositoryContainer.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/di/ServiceContainer.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/KerdyApplication.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/firebase/analytics/KerdyAnalytics.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/EventDetailActivity.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/EventDetailFragmentStateAdpater.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/EventDetailViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/EventTag.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/EventCommentFragment.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/information/EventInfoFragment.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/participant/EventParticipantFragment.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/uistate/EventDetailUiState.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/MainActivity.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/EventFragment.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/EventViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/events/EventsFragment.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/myProfile/adapter/JobsViewHolder.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/myProfile/uiState/ActivityUiState.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/utils/DateStringFormat.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/utils/bindingadapter/ImageViewBindingAdapter.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/utils/bindingadapter/SwipeRefreshLayoutBindingAdapter.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/utils/extension/IntExt.kt
  android/2023-emmsale/app/src/main/res/drawable/bg_eventdetail_tab.xml
  android/2023-emmsale/app/src/main/res/drawable/bg_eventdetail_tag.xml
  android/2023-emmsale/app/src/main/res/drawable/bg_eventinformation_urlbutton.xml
  android/2023-emmsale/app/src/main/res/drawable/ic_all_arrowback.xml
  android/2023-emmsale/app/src/main/res/drawable/ic_all_errorimage.xml
  android/2023-emmsale/app/src/main/res/drawable/ic_eventdetail_date.xml
  android/2023-emmsale/app/src/main/res/drawable/ic_eventdetail_place.xml
  android/2023-emmsale/app/src/main/res/layout/activity_event_detail.xml
  android/2023-emmsale/app/src/main/res/layout/activity_main.xml
  android/2023-emmsale/app/src/main/res/layout/fragment_event_comment.xml
  android/2023-emmsale/app/src/main/res/layout/fragment_event_information.xml
  android/2023-emmsale/app/src/main/res/layout/fragment_event_participant.xml
  android/2023-emmsale/app/src/main/res/layout/fragment_events.xml
  android/2023-emmsale/app/src/main/res/values/colors.xml
  android/2023-emmsale/app/src/main/res/values/strings.xml
  android/2023-emmsale/app/src/main/res/values/styles.xml
Labels: 안드로이드

#193 Feature/#190 참여자 목록 탭 화면 구현
  android/2023-emmsale/app/build.gradle.kts
  android/2023-emmsale/app/src/main/java/com/emmsale/data/common/ServiceFactory.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/participant/Participant.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/participant/ParticipantRepository.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/participant/ParticipantRepositoryImpl.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/participant/ParticipantService.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/participant/dto/CompanionRequestBody.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/participant/dto/ParticipantApiModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/participant/dto/ParticipantRequestBody.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/uid/UidRepository.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/uid/UidRepositoryImpl.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/di/RepositoryContainer.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/di/ServiceContainer.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/EventDetailViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/participant/EventParticipantAdapter.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/participant/EventParticipantFragment.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/participant/EventParticipantViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/participant/ParticipantFragmentDialog.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/participant/uistate/ParticipantUiState.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/participant/uistate/ParticipantsUiState.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/participant/uistate/ParticipationStatusUiState.kt
  android/2023-emmsale/app/src/main/res/layout/activity_event_detail.xml
  android/2023-emmsale/app/src/main/res/layout/fragment_event_information.xml
  android/2023-emmsale/app/src/main/res/layout/fragment_event_participant.xml
  android/2023-emmsale/app/src/main/res/layout/fragmentdialog_participant.xml
  android/2023-emmsale/app/src/main/res/layout/item_participant.xml
  android/2023-emmsale/app/src/main/res/values/colors.xml
  android/2023-emmsale/app/src/main/res/values/strings.xml
Labels: 안드로이드, 기능 추가, High Priority

#195 Feature/#194 댓글 단건 조회 api 구현
  backend/emm-sale/src/docs/asciidoc/index.adoc
  backend/emm-sale/src/main/java/com/emmsale/comment/api/CommentApi.java
  backend/emm-sale/src/main/java/com/emmsale/comment/application/CommentQueryService.java
  backend/emm-sale/src/main/java/com/emmsale/comment/application/dto/CommentHierarchyResponse.java
  backend/emm-sale/src/main/java/com/emmsale/comment/domain/Comment.java
  backend/emm-sale/src/main/java/com/emmsale/comment/domain/CommentRepository.java
  backend/emm-sale/src/main/resources/http/comment.http
  backend/emm-sale/src/main/resources/static/docs/index.html
  backend/emm-sale/src/test/java/com/emmsale/comment/api/CommentApiTest.java
  backend/emm-sale/src/test/java/com/emmsale/comment/application/CommentQueryServiceTest.java
  backend/emm-sale/src/test/java/com/emmsale/comment/domain/CommentRepositoryTest.java
Labels: 백엔드, 기능 추가, High Priority

#203 Feature/#98 댓글 화면 구현
  android/2023-emmsale/app/src/main/AndroidManifest.xml
  android/2023-emmsale/app/src/main/java/com/emmsale/data/comment/Comment.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/comment/CommentRepository.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/comment/CommentRepositoryImpl.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/comment/CommentService.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/comment/dto/CommentApiModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/comment/dto/CommentFamilyApiModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/comment/dto/SaveCommentRequestBody.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/comment/dto/UpdateCommentRequestBody.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/comment/mapper/CommentMapper.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/di/RepositoryContainer.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/di/ServiceContainer.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/childComments/ChildCommentsActivity.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/childComments/ChildCommentsViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/childComments/adapter/ChildCommentViewHolder.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/childComments/adapter/ChildCommentsAdapter.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/childComments/uiState/ChildCommentsScreenUiState.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/childComments/uiState/CommentUiState.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/comment/CommentsFragment.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/comment/CommentsViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/comment/adpater/CommentViewHolder.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/comment/adpater/CommentsAdapter.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/comment/uiState/CommentUiState.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/comment/uiState/CommentsScreenUiState.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/EventDetailActivity.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/EventDetailFragmentStateAdpater.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/MainActivity.kt
  android/2023-emmsale/app/src/main/res/drawable/bg_all_dialog.xml
  android/2023-emmsale/app/src/main/res/drawable/bg_comments_commenteditview.xml
  android/2023-emmsale/app/src/main/res/drawable/bg_commentsmenu_dialog.xml
  android/2023-emmsale/app/src/main/res/drawable/ic_all_upbutton.xml
  android/2023-emmsale/app/src/main/res/drawable/ic_childcomment_arrow.xml
  android/2023-emmsale/app/src/main/res/drawable/ic_comment_delete.xml
  android/2023-emmsale/app/src/main/res/drawable/ic_comment_menubutton.xml
  android/2023-emmsale/app/src/main/res/drawable/img_commentsmenu_topdecoration.xml
  android/2023-emmsale/app/src/main/res/layout/activity_child_comments.xml
  android/2023-emmsale/app/src/main/res/layout/dialog_comment_delete.xml
  android/2023-emmsale/app/src/main/res/layout/dialog_comments_menu.xml
  android/2023-emmsale/app/src/main/res/layout/fragment_comments.xml
  android/2023-emmsale/app/src/main/res/layout/item_childcomments_childcomment.xml
  android/2023-emmsale/app/src/main/res/layout/item_comments_comments.xml
  android/2023-emmsale/app/src/main/res/values/strings.xml
  android/2023-emmsale/app/src/main/res/values/themes.xml
  android/2023-emmsale/app/src/test/java/com/emmsale/data/comment/CommentRepositoryImplTest.kt
  android/2023-emmsale/app/src/test/java/com/emmsale/data/comment/CommentServiceTest.kt
  android/2023-emmsale/app/src/test/java/com/emmsale/data/member/MemberRepositoryImplTest.kt
Labels: 안드로이드, 기능 추가, High Priority

#209 Feature/#208 댓글 조회 로직 변경
  android/2023-emmsale/app/src/main/java/com/emmsale/data/comment/Comment.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/comment/CommentRepository.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/comment/CommentRepositoryImpl.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/comment/mapper/CommentMapper.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/di/RepositoryContainer.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/childComments/uiState/CommentUiState.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/comment/uiState/CommentUiState.kt
  android/2023-emmsale/app/src/test/java/com/emmsale/data/comment/CommentRepositoryImplTest.kt
Labels: 안드로이드, 기능 추가, High Priority

#211 fix: 알림 보관함에 확장 화살표 아이콘 반대로 보이는 버그 수정
  android/2023-emmsale/app/src/main/res/layout/item_notification_header.xml
Labels: 안드로이드, Low Priority

#215 발표용 설정 화면 추가
  android/2023-emmsale/app/src/main/java/com/emmsale/data/comment/CommentRepository.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/comment/CommentRepositoryImpl.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/comment/CommentService.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/comment/dto/CommentApiModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/comment/mapper/CommentMapper.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/views/FilterTag.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/views/IconTextButton.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/childComments/ChildCommentsViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/childComments/adapter/ChildCommentViewHolder.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/childComments/adapter/ChildCommentsAdapter.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/childComments/uiState/ChildCommentsScreenUiState.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/childComments/uiState/CommentUiState.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/comment/CommentsFragment.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/comment/CommentsViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/comment/adpater/CommentViewHolder.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/comment/adpater/CommentsAdapter.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/MainActivity.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/conference/ConferenceViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/conferenceFilter/ConferenceFilterViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/notificationBox/NotificationBoxActivity.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/notificationBox/NotificationBoxViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/notificationBox/recyclerview/header/NotificationBoxHeaderAdapter.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/setting/SettingFragment.kt
  android/2023-emmsale/app/src/main/res/layout/fragment_setting.xml
  android/2023-emmsale/app/src/main/res/values/strings.xml
  android/2023-emmsale/app/src/test/java/com/emmsale/data/comment/CommentRepositoryImplTest.kt
  android/2023-emmsale/app/src/test/java/com/emmsale/data/comment/CommentServiceTest.kt
Labels: 안드로이드, 기능 추가, High Priority

#226 Fix/#223 이벤트 상세 조회 시 상태 잘못 계산하는 오류 수정
  backend/emm-sale/src/main/java/com/emmsale/event/application/dto/EventDetailResponse.java
  backend/emm-sale/src/test/java/com/emmsale/event/application/dto/EventDetailResponseTest.java
Labels: 버그, 백엔드

#239 Feature/#229 프로필 화면 디자인 변경
  android/2023-emmsale/app/src/main/java/com/emmsale/data/activity/ActivityType.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/member/mapper/MemberMapper.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/views/CategoryTag.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/conferenceFilter/ConferenceFilterViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/myProfile/MyProfileFragment.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/myProfile/MyProfileViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/myProfile/adapter/JobsAdapter.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/myProfile/adapter/JobsViewHolder.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/myProfile/uiState/MyProfileScreenUiState.kt
  android/2023-emmsale/app/src/main/res/drawable/bg_myprofile_categorytag.xml
  android/2023-emmsale/app/src/main/res/layout/fragment_my_profile.xml
  android/2023-emmsale/app/src/main/res/layout/item_myprofile_jobs.xml
Labels: 안드로이드, 기능 추가, High Priority

#233 Fix/#225 오픈 프로필 url 없으면 exception 발생하도록 수정
  backend/emm-sale/src/main/java/com/emmsale/GlobalControllerAdvice.java
  backend/emm-sale/src/main/java/com/emmsale/member/domain/Member.java
  backend/emm-sale/src/main/java/com/emmsale/notification/application/FirebaseCloudMessageClient.java
  backend/emm-sale/src/main/java/com/emmsale/notification/application/NotificationCommandService.java
  backend/emm-sale/src/main/java/com/emmsale/notification/exception/NotificationExceptionType.java
  backend/emm-sale/src/test/java/com/emmsale/member/application/MemberUpdateServiceTest.java
Labels: 버그, 백엔드, High Priority

#255 fix : 알림 같이 가기 요청이 이미 존재한 경우 다시 알림을 보낼 수 없도록 validation 추가
  backend/emm-sale/src/main/java/com/emmsale/notification/application/NotificationCommandService.java
  backend/emm-sale/src/main/java/com/emmsale/notification/domain/NotificationRepository.java
  backend/emm-sale/src/main/java/com/emmsale/notification/exception/NotificationExceptionType.java
  backend/emm-sale/src/main/resources/static/docs/index.html
  backend/emm-sale/src/test/java/com/emmsale/notification/domain/NotificationRepositoryTest.java
Labels: 버그, 백엔드, High Priority

#238 Feature/#235 행사 필터 초기화
  android/2023-emmsale/app/build.gradle.kts
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/extension/AlertDialogExt.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/conferenceFilter/ConferenceFilterActivity.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/conferenceFilter/ConferenceFilterViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/conferenceFilter/uistate/ConferenceFiltersUiState.kt
  android/2023-emmsale/app/src/main/res/drawable/ic_conference_filter_clear.xml
  android/2023-emmsale/app/src/main/res/layout/activity_conference_filter.xml
  android/2023-emmsale/app/src/main/res/menu/menu_conference_filter.xml
  android/2023-emmsale/app/src/main/res/values/strings.xml
  android/2023-emmsale/app/src/main/res/values/themes.xml
Labels: Low Priority

#259 Feature/#230 행사 목록 조회 api 형식 변경 반영
  android/2023-emmsale/app/src/main/java/com/emmsale/data/conference/ConferenceRepository.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/conference/ConferenceRepositoryImpl.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/conference/ConferenceService.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/conference/ConferenceStatus.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/conference/ConferenceFragment.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/conference/ConferenceViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/conferenceFilter/ConferenceFilterViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/conferenceFilter/uistate/ConferenceFilterDateUiState.kt
  android/2023-emmsale/app/src/main/res/values/strings.xml
Labels: High Priority

#218 Feature/#217-행사 목록 조회 API 필터링 옵션 수정
  backend/emm-sale/src/docs/asciidoc/index.adoc
  backend/emm-sale/src/main/java/com/emmsale/event/api/EventApi.java
  backend/emm-sale/src/main/java/com/emmsale/event/application/EventService.java
  backend/emm-sale/src/main/java/com/emmsale/event/domain/repository/EventRepository.java
  backend/emm-sale/src/main/java/com/emmsale/event/domain/repository/EventSpecification.java
  backend/emm-sale/src/main/java/com/emmsale/event/domain/repository/EventTagRepository.java
  backend/emm-sale/src/main/java/com/emmsale/event/exception/EventExceptionType.java
  backend/emm-sale/src/main/java/com/emmsale/tag/domain/TagRepository.java
  backend/emm-sale/src/main/resources/http/event.http
  backend/emm-sale/src/test/java/com/emmsale/event/api/EventApiTest.java
  backend/emm-sale/src/test/java/com/emmsale/event/application/EventServiceTest.java
Labels: 백엔드, 기능 추가, High Priority

#250 Fix/#232 프로필에 동일한 활동을 중복해서 등록할 수 있는 버그
  backend/emm-sale/src/main/java/com/emmsale/member/application/MemberActivityService.java
  backend/emm-sale/src/main/java/com/emmsale/member/exception/MemberExceptionType.java
  backend/emm-sale/src/test/java/com/emmsale/member/application/MemberActivityServiceTest.java
  backend/emm-sale/src/test/java/com/emmsale/member/application/MemberQueryServiceTest.java
  backend/emm-sale/src/test/resources/data-test.sql
Labels: 버그, 백엔드, Low Priority

#260 Feature/#258 함께해요 게시글 수정 api 추가
  backend/emm-sale/src/docs/asciidoc/index.adoc
  backend/emm-sale/src/main/java/com/emmsale/activity/application/ActivityService.java
  backend/emm-sale/src/main/java/com/emmsale/event/api/EventApi.java
  backend/emm-sale/src/main/java/com/emmsale/event/application/EventService.java
  backend/emm-sale/src/main/java/com/emmsale/event/application/dto/ParticipateUpdateRequest.java
  backend/emm-sale/src/main/java/com/emmsale/event/domain/Event.java
  backend/emm-sale/src/main/java/com/emmsale/event/domain/Participant.java
  backend/emm-sale/src/main/java/com/emmsale/event/exception/EventExceptionType.java
  backend/emm-sale/src/main/java/com/emmsale/member/domain/Member.java
  backend/emm-sale/src/main/resources/http/event.http
  backend/emm-sale/src/test/java/com/emmsale/comment/domain/CommentRepositoryTest.java
  backend/emm-sale/src/test/java/com/emmsale/event/api/EventApiTest.java
  backend/emm-sale/src/test/java/com/emmsale/event/application/EventServiceTest.java
  backend/emm-sale/src/test/java/com/emmsale/event/domain/EventTest.java
  backend/emm-sale/src/test/java/com/emmsale/event/domain/ParticipantTest.java
  backend/emm-sale/src/test/java/com/emmsale/member/domain/MemberRepositoryTest.java
Labels: 백엔드, 기능 추가, High Priority

#269 Feature/#248 알림 삭제 기능
  backend/emm-sale/src/docs/asciidoc/index.adoc
  backend/emm-sale/src/main/java/com/emmsale/notification/api/NotificationApi.java
  backend/emm-sale/src/main/java/com/emmsale/notification/application/NotificationCommandService.java
  backend/emm-sale/src/main/java/com/emmsale/notification/domain/Notification.java
  backend/emm-sale/src/main/java/com/emmsale/notification/exception/NotificationExceptionType.java
  backend/emm-sale/src/test/java/com/emmsale/notification/api/NotificationApiTest.java
  backend/emm-sale/src/test/java/com/emmsale/notification/application/NotificationCommandServiceTest.java
Labels: 백엔드, 기능 추가, Low Priority

#262 Feature/#240 사용자 차단 기능
  backend/emm-sale/src/docs/asciidoc/index.adoc
  backend/emm-sale/src/main/java/com/emmsale/block/api/BlockApi.java
  backend/emm-sale/src/main/java/com/emmsale/block/application/BlockCommandService.java
  backend/emm-sale/src/main/java/com/emmsale/block/application/dto/BlockRequest.java
  backend/emm-sale/src/main/java/com/emmsale/block/domain/Block.java
  backend/emm-sale/src/main/java/com/emmsale/block/domain/BlockRepository.java
  backend/emm-sale/src/main/java/com/emmsale/block/exception/BlockException.java
  backend/emm-sale/src/main/java/com/emmsale/block/exception/BlockExceptionType.java
  backend/emm-sale/src/main/java/com/emmsale/comment/api/CommentApi.java
  backend/emm-sale/src/main/java/com/emmsale/comment/application/CommentQueryService.java
  backend/emm-sale/src/main/java/com/emmsale/comment/application/dto/CommentHierarchyResponse.java
  backend/emm-sale/src/main/java/com/emmsale/comment/application/dto/CommentResponse.java
  backend/emm-sale/src/main/java/com/emmsale/comment/domain/Comment.java
  backend/emm-sale/src/main/java/com/emmsale/comment/exception/CommentExceptionType.java
  backend/emm-sale/src/main/resources/schema.sql
  backend/emm-sale/src/test/java/com/emmsale/block/api/BlockApiTest.java
  backend/emm-sale/src/test/java/com/emmsale/block/application/BlockCommandServiceTest.java
  backend/emm-sale/src/test/java/com/emmsale/comment/api/CommentApiTest.java
  backend/emm-sale/src/test/java/com/emmsale/comment/application/CommentQueryServiceTest.java
  backend/emm-sale/src/test/java/com/emmsale/comment/domain/CommentRepositoryTest.java
  backend/emm-sale/src/test/java/com/emmsale/comment/domain/CommentTest.java
Labels: 백엔드, 기능 추가, High Priority

#279 Feature/#278 event 엔티티 태그 즉시로딩 제거
  backend/emm-sale/src/main/java/com/emmsale/event/domain/Event.java
  backend/emm-sale/src/main/java/com/emmsale/event/domain/EventTag.java
  backend/emm-sale/src/test/java/com/emmsale/event/application/EventServiceTest.java
Labels: 백엔드, 리팩터링, Low Priority

#267 Feature/#266 토마스 코드 리팩토링
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/service/KerdyFirebaseMessagingService.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/CommentFragment.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/CommentViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/childComment/ChildCommentActivity.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/childComment/ChildCommentViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/childComment/recyclerView/ChildCommentAdapter.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/childComment/recyclerView/ChildCommentViewHolder.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/childComment/uiState/ChildCommentsUiState.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/childComment/uiState/CommentUiState.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/recyclerView/CommentViewHolder.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/recyclerView/CommentsAdapter.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/uiState/CommentUiState.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/uiState/CommentsUiState.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/recruitment/EventRecruitmentFragment.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/recruitment/RecruitmentFragmentDialog.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/myProfile/MyProfileFragment.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/myProfile/MyProfileViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/myProfile/recyclerView/ActivitiesAdapter.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/myProfile/recyclerView/ActivitiesAdapterDecoration.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/myProfile/recyclerView/ActivityViewHolder.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/myProfile/uiState/MyProfileUiState.kt
  android/2023-emmsale/app/src/main/res/layout/activity_child_comments.xml
  android/2023-emmsale/app/src/main/res/layout/fragment_comments.xml
  android/2023-emmsale/app/src/main/res/layout/fragment_my_profile.xml
  android/2023-emmsale/app/src/main/res/values/strings.xml
Labels: 안드로이드, 리팩터링

#275 Feature/#273 행사에 신청기간 정보 추가
  backend/emm-sale/src/main/java/com/emmsale/event/application/EventService.java
  backend/emm-sale/src/main/java/com/emmsale/event/application/dto/EventDetailRequest.java
  backend/emm-sale/src/main/java/com/emmsale/event/application/dto/EventDetailResponse.java
  backend/emm-sale/src/main/java/com/emmsale/event/application/dto/EventResponse.java
  backend/emm-sale/src/main/java/com/emmsale/event/domain/Event.java
  backend/emm-sale/src/main/java/com/emmsale/event/domain/EventPeriod.java
  backend/emm-sale/src/main/java/com/emmsale/event/domain/EventStatus.java
  backend/emm-sale/src/main/java/com/emmsale/event/domain/repository/EventSpecification.java
  backend/emm-sale/src/main/java/com/emmsale/event/exception/EventExceptionType.java
  backend/emm-sale/src/main/resources/data.sql
  backend/emm-sale/src/main/resources/schema.sql
  backend/emm-sale/src/test/java/com/emmsale/comment/application/CommentCommandServiceTest.java
  backend/emm-sale/src/test/java/com/emmsale/event/EventFixture.java
  backend/emm-sale/src/test/java/com/emmsale/event/api/EventApiTest.java
  backend/emm-sale/src/test/java/com/emmsale/event/application/EventServiceTest.java
  backend/emm-sale/src/test/java/com/emmsale/event/application/dto/EventDetailResponseTest.java
  backend/emm-sale/src/test/java/com/emmsale/event/domain/EventStatusTest.java
  backend/emm-sale/src/test/java/com/emmsale/event/domain/EventTest.java
Labels: 백엔드, 기능 추가, High Priority

#294 Feature/#284 대댓글 알림 받기
  android/2023-emmsale/app/build.gradle.kts
  android/2023-emmsale/app/src/main/java/com/emmsale/data/conference/Conference.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/conference/dto/ConferenceApiModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/conference/mapper/ConferenceMapper.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/conference/mapper/ConferenceStatusMapper.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/eventApplyStatus/EventApplyStatus.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/eventApplyStatus/EventApplyStatusRepository.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/eventApplyStatus/EventApplyStatusRepositoryImpl.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/eventdetail/EventDetail.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/eventdetail/mapper/EventDetailMapper.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/extension/ContextExt.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/service/KerdyFirebaseMessagingService.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/EventDetailActivity.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/childComment/ChildCommentActivity.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/uistate/EventDetailUiState.kt
  android/2023-emmsale/app/src/main/res/layout/activity_event_detail.xml
  android/2023-emmsale/app/src/main/res/values/strings.xml
Labels: 안드로이드, 기능 추가

#293 refactor: 함께해요 게시글 삭제 API 엔드포인트 변경
  backend/emm-sale/src/docs/asciidoc/index.adoc
  backend/emm-sale/src/main/java/com/emmsale/event/api/RecruitmentPostApi.java
  backend/emm-sale/src/main/java/com/emmsale/event/application/RecruitmentPostCommandService.java
  backend/emm-sale/src/main/java/com/emmsale/event/application/dto/RecruitmentPostResponse.java
  backend/emm-sale/src/main/java/com/emmsale/event/exception/EventExceptionType.java
  backend/emm-sale/src/test/java/com/emmsale/event/api/RecruitmentPostApiTest.java
  backend/emm-sale/src/test/java/com/emmsale/event/application/RecruitmentPostCommandServiceTest.java
  backend/emm-sale/src/test/java/com/emmsale/event/application/RecruitmentPostQueryServiceTest.java
Labels: 백엔드, High Priority

#289 Feature/#243 대댓글 업데이트 알림 기능 구현
  backend/emm-sale/src/docs/asciidoc/index.adoc
  backend/emm-sale/src/main/java/com/emmsale/activity/application/ActivityService.java
  backend/emm-sale/src/main/java/com/emmsale/comment/application/CommentCommandService.java
  backend/emm-sale/src/main/java/com/emmsale/comment/domain/Comment.java
  backend/emm-sale/src/main/java/com/emmsale/comment/event/UpdateNotificationEvent.java
  backend/emm-sale/src/main/java/com/emmsale/event_publisher/EventPublisher.java
  backend/emm-sale/src/main/java/com/emmsale/notification/api/FcmTokenApi.java
  backend/emm-sale/src/main/java/com/emmsale/notification/api/NotificationApi.java
  backend/emm-sale/src/main/java/com/emmsale/notification/api/RequestNotificationApi.java
  backend/emm-sale/src/main/java/com/emmsale/notification/application/FcmTokenRegisterService.java
  backend/emm-sale/src/main/java/com/emmsale/notification/application/FirebaseCloudMessageClient.java
  backend/emm-sale/src/main/java/com/emmsale/notification/application/NotificationCommandService.java
  backend/emm-sale/src/main/java/com/emmsale/notification/application/NotificationQueryService.java
  backend/emm-sale/src/main/java/com/emmsale/notification/application/RequestNotificationCommandService.java
  backend/emm-sale/src/main/java/com/emmsale/notification/application/RequestNotificationQueryService.java
  backend/emm-sale/src/main/java/com/emmsale/notification/application/UpdateNotificationCommandService.java
  backend/emm-sale/src/main/java/com/emmsale/notification/application/dto/NotificationModifyRequest.java
  backend/emm-sale/src/main/java/com/emmsale/notification/application/dto/NotificationResponse.java
  backend/emm-sale/src/main/java/com/emmsale/notification/application/dto/RequestNotificationMessage.java
  backend/emm-sale/src/main/java/com/emmsale/notification/application/dto/RequestNotificationModifyRequest.java
  backend/emm-sale/src/main/java/com/emmsale/notification/application/dto/RequestNotificationRequest.java
  backend/emm-sale/src/main/java/com/emmsale/notification/application/dto/RequestNotificationResponse.java
  backend/emm-sale/src/main/java/com/emmsale/notification/application/dto/UpdateNotificationMessage.java
  backend/emm-sale/src/main/java/com/emmsale/notification/application/generator/NotificationMessageGenerator.java
  backend/emm-sale/src/main/java/com/emmsale/notification/application/generator/RequestNotificationMessageGenerator.java
  backend/emm-sale/src/main/java/com/emmsale/notification/application/generator/UpdateNotificationMessageGenerator.java
  backend/emm-sale/src/main/java/com/emmsale/notification/domain/RequestNotification.java
  backend/emm-sale/src/main/java/com/emmsale/notification/domain/RequestNotificationRepository.java
  backend/emm-sale/src/main/java/com/emmsale/notification/domain/RequestNotificationStatus.java
  backend/emm-sale/src/main/java/com/emmsale/notification/domain/UpdateNotification.java
  backend/emm-sale/src/main/java/com/emmsale/notification/domain/UpdateNotificationRepository.java
  backend/emm-sale/src/main/java/com/emmsale/notification/domain/UpdateNotificationType.java
  backend/emm-sale/src/main/java/com/emmsale/notification/exception/NotificationExceptionType.java
  backend/emm-sale/src/main/resources/data.sql
  backend/emm-sale/src/main/resources/http/notification.http
  backend/emm-sale/src/main/resources/schema.sql
  backend/emm-sale/src/main/resources/static/docs/index.html
  backend/emm-sale/src/test/java/com/emmsale/comment/application/CommentCommandServiceTest.java
  backend/emm-sale/src/test/java/com/emmsale/notification/api/FcmTokenApiTest.java
  backend/emm-sale/src/test/java/com/emmsale/notification/api/RequestNotificationApiTest.java
  backend/emm-sale/src/test/java/com/emmsale/notification/application/FcmTokenRegisterServiceTest.java
  backend/emm-sale/src/test/java/com/emmsale/notification/application/RequestNotificationCommandServiceTest.java
  backend/emm-sale/src/test/java/com/emmsale/notification/application/UpdateNotificationCommandServiceTest.java
  backend/emm-sale/src/test/java/com/emmsale/notification/application/generator/UpdateNotificationMessageGeneratorTest.java
  backend/emm-sale/src/test/java/com/emmsale/notification/domain/RequestNotificationRepositoryTest.java
  backend/emm-sale/src/test/java/com/emmsale/notification/domain/UpdateNotificationTypeTest.java
  backend/emm-sale/src/test/resources/data-test.sql
Labels: 백엔드, 기능 추가

#308 hotfix : 알림 중복 요청 기능 수정
  backend/emm-sale/src/main/java/com/emmsale/comment/application/CommentCommandService.java
  backend/emm-sale/src/main/java/com/emmsale/comment/domain/Comment.java
  backend/emm-sale/src/main/resources/static/docs/index.html
  backend/emm-sale/src/test/java/com/emmsale/comment/application/CommentCommandServiceTest.java
Labels: 버그, 백엔드, High Priority

#280 Feature/#249 행사 관심 태그 crd 구현
  backend/emm-sale/src/docs/asciidoc/index.adoc
  backend/emm-sale/src/main/java/com/emmsale/member/api/InterestTagApi.java
  backend/emm-sale/src/main/java/com/emmsale/member/application/InterestTagService.java
  backend/emm-sale/src/main/java/com/emmsale/member/application/dto/InterestTagAddRequest.java
  backend/emm-sale/src/main/java/com/emmsale/member/application/dto/InterestTagDeleteRequest.java
  backend/emm-sale/src/main/java/com/emmsale/member/application/dto/InterestTagResponse.java
  backend/emm-sale/src/main/java/com/emmsale/member/domain/InterestTag.java
  backend/emm-sale/src/main/java/com/emmsale/member/domain/InterestTagRepository.java
  backend/emm-sale/src/main/java/com/emmsale/member/exception/MemberExceptionType.java
  backend/emm-sale/src/main/resources/http/interest-tag.http
  backend/emm-sale/src/test/java/com/emmsale/member/api/InterestTagApiTest.java
  backend/emm-sale/src/test/java/com/emmsale/member/api/MemberApiTest.java
  backend/emm-sale/src/test/java/com/emmsale/member/application/InterestTagServiceTest.java
Labels: 백엔드, 기능 추가, Low Priority

#304 Feature/#302 컨퍼런스 목록 화면에서 필터 제거
  android/2023-emmsale/app/build.gradle.kts
  android/2023-emmsale/app/src/main/java/com/emmsale/data/notification/RecruitmentNotificationStatus.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/views/FilterTag.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/views/IconTextButton.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/EventFragment.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/conference/ConferenceFragment.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/conference/ConferenceViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/conference/uistate/ConferenceSelectedFilteringDateOptionUiState.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/conference/uistate/ConferenceSelectedFilteringUiState.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/conferenceFilter/ConferenceFilterActivity.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/notificationBox/NotificationBoxActivity.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/notificationBox/NotificationBoxFragmentStateAdapter.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/notificationBox/otherNotification/PrimaryNotificationFragment.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/notificationBox/recruitmentNotification/RecruitmentNotificationFragment.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/notificationBox/recruitmentNotification/RecruitmentNotificationViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/notificationBox/recruitmentNotification/recyclerview/body/RecruitmentNotificationBodyAdapter.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/notificationBox/recruitmentNotification/recyclerview/body/RecruitmentNotificationBodyDiffUtil.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/notificationBox/recruitmentNotification/recyclerview/header/RecruitmentNotificationHeaderAdapter.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/notificationBox/recruitmentNotification/recyclerview/header/RecruitmentNotificationHeaderDiffUtil.kt
  android/2023-emmsale/app/src/main/res/drawable/bg_eventdetail_tab.xml
  android/2023-emmsale/app/src/main/res/drawable/ic_all_more.xml
  android/2023-emmsale/app/src/main/res/drawable/ic_conference_filtering_option_remove.png
  android/2023-emmsale/app/src/main/res/drawable/ic_conference_filtering_option_remove_12.xml
  android/2023-emmsale/app/src/main/res/layout/activity_event_detail.xml
  android/2023-emmsale/app/src/main/res/layout/dialog_recruitment_accepted.xml
  android/2023-emmsale/app/src/main/res/layout/dialog_recruitment_reject_confirm.xml
  android/2023-emmsale/app/src/main/res/layout/item_recruitment_notification_body.xml
  android/2023-emmsale/app/src/main/res/layout/item_recruitment_notification_header.xml
  android/2023-emmsale/app/src/main/res/values/custom_views.xml
  android/2023-emmsale/app/src/main/res/values/styles.xml
  android/2023-emmsale/app/src/main/res/values/themes.xml
Labels: 안드로이드, Low Priority

#299 Feature/#291 컨퍼런스 같이가요 거절 수락
  android/2023-emmsale/app/src/main/AndroidManifest.xml
  android/2023-emmsale/app/src/main/java/com/emmsale/data/notification/NotificationRepository.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/notification/NotificationRepositoryImpl.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/notification/NotificationService.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/notification/RecruitmentNotification.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/notification/RecruitmentNotificationApiModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/notification/RecruitmentStatus.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/notification/mapper/NotificationMapper.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/conference/ConferenceFragment.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/conference/ConferenceViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/conference/recyclerview/ConferenceDiffUtil.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/conference/recyclerview/ConferenceRecyclerViewAdapter.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/conference/recyclerview/ConferenceRecyclerViewDivider.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/conference/recyclerview/ConferenceViewHolder.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/conference/uistate/ConferenceItemUiState.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/conference/uistate/ConferenceUiState.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/conference/uistate/ConferencesUiState.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/conferenceFilter/ConferenceFilterActivity.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/conferenceFilter/ConferenceFilterViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/conferenceFilter/uistate/ConferenceFilterUiState.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/notificationBox/NotificationBoxActivity.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/notificationBox/NotificationBoxFragmentStateAdapter.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/notificationBox/primaryNotification/PrimaryNotificationFragment.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/notificationBox/recruitmentNotification/RecruitmentNotificationFragment.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/notificationBox/recruitmentNotification/RecruitmentNotificationViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/notificationBox/recruitmentNotification/dialog/RecruitmentAcceptedDialog.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/notificationBox/recruitmentNotification/dialog/RecruitmentRejectConfirmDialog.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/notificationBox/recruitmentNotification/recyclerview/body/RecruitmentNotificationBodyClickListener.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/notificationBox/recruitmentNotification/recyclerview/header/RecruitmentNotificationHeaderClickListener.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/notificationBox/recruitmentNotification/uistate/RecruitmentNotificationBodyUiState.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/notificationBox/recruitmentNotification/uistate/RecruitmentNotificationHeaderUiState.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/notificationBox/recruitmentNotification/uistate/RecruitmentNotificationUiState.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/notificationBox/recruitmentNotification/uistate/RecruitmentNotificationsUiState.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/notificationBox/recruitmentNotification/uistate/RecruitmentUiState.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/onboarding/OnboardingViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/onboarding/uistate/OnboardingUiState.kt
  android/2023-emmsale/app/src/main/res/layout/dialog_recruitment_accepted.xml
  android/2023-emmsale/app/src/main/res/layout/dialog_recruitment_reject_confirm.xml
  android/2023-emmsale/app/src/main/res/layout/fragment_conference.xml
  android/2023-emmsale/app/src/main/res/layout/fragment_primary_notification.xml
  android/2023-emmsale/app/src/main/res/layout/item_conference.xml
  android/2023-emmsale/app/src/main/res/layout/item_recruitment_notification_body.xml
  android/2023-emmsale/app/src/main/res/layout/item_recruitment_notification_header.xml
Labels: 안드로이드, 기능 추가, High Priority

#300 Feature/#296 함께 가기 요청 알림 목록 조회 시 is read status 반환
  backend/emm-sale/src/docs/asciidoc/index.adoc
  backend/emm-sale/src/main/java/com/emmsale/notification/api/RequestNotificationApi.java
  backend/emm-sale/src/main/java/com/emmsale/notification/application/RequestNotificationCommandService.java
  backend/emm-sale/src/main/java/com/emmsale/notification/application/dto/RequestNotificationResponse.java
  backend/emm-sale/src/main/java/com/emmsale/notification/domain/RequestNotification.java
  backend/emm-sale/src/main/resources/http/fcmToken.http
  backend/emm-sale/src/main/resources/http/request-notification.http
  backend/emm-sale/src/main/resources/schema.sql
  backend/emm-sale/src/main/resources/static/docs/index.html
  backend/emm-sale/src/test/java/com/emmsale/notification/api/RequestNotificationApiTest.java
  backend/emm-sale/src/test/java/com/emmsale/notification/application/RequestNotificationCommandServiceTest.java
Labels: 백엔드, 기능 추가, High Priority

#310 Feature/#297 댓글 알림 조회 api, 읽음 상태 변경 api 및 is read 추가
  backend/emm-sale/src/docs/asciidoc/index.adoc
  backend/emm-sale/src/main/java/com/emmsale/member/exception/MemberExceptionType.java
  backend/emm-sale/src/main/java/com/emmsale/notification/api/UpdateNotificationApi.java
  backend/emm-sale/src/main/java/com/emmsale/notification/application/NotificationEventListener.java
  backend/emm-sale/src/main/java/com/emmsale/notification/application/UpdateNotificationCommandService.java
  backend/emm-sale/src/main/java/com/emmsale/notification/application/UpdateNotificationQueryService.java
  backend/emm-sale/src/main/java/com/emmsale/notification/application/dto/UpdateNotificationResponse.java
  backend/emm-sale/src/main/java/com/emmsale/notification/domain/UpdateNotification.java
  backend/emm-sale/src/main/java/com/emmsale/notification/domain/UpdateNotificationRepository.java
  backend/emm-sale/src/main/resources/schema.sql
  backend/emm-sale/src/test/java/com/emmsale/notification/api/UpdateNotificationApiTest.java
  backend/emm-sale/src/test/java/com/emmsale/notification/application/NotificationEventListenerTest.java
  backend/emm-sale/src/test/java/com/emmsale/notification/application/UpdateNotificationCommandServiceTest.java
  backend/emm-sale/src/test/java/com/emmsale/notification/application/UpdateNotificationQueryServiceTest.java
  backend/emm-sale/src/test/java/com/emmsale/notification/domain/UpdateNotificationRepositoryTest.java
  backend/emm-sale/src/test/java/com/emmsale/notification/domain/UpdateNotificationTest.java
Labels: 백엔드, 기능 추가, High Priority

#295 태그 목록 조회 API 구현
  backend/emm-sale/src/docs/asciidoc/index.adoc
  backend/emm-sale/src/main/java/com/emmsale/tag/api/TagApi.java
  backend/emm-sale/src/main/java/com/emmsale/tag/application/TagQueryService.java
  backend/emm-sale/src/main/java/com/emmsale/tag/application/dto/TagResponse.java
  backend/emm-sale/src/main/resources/http/tag.http
  backend/emm-sale/src/test/java/com/emmsale/event/api/EventApiTest.java
  backend/emm-sale/src/test/java/com/emmsale/tag/api/TagApiTest.java
  backend/emm-sale/src/test/java/com/emmsale/tag/application/TagQueryServiceTest.java
Labels: 백엔드, 기능 추가, Low Priority

#318 Feature/#317 함께해요 게시글 단건 조회
  backend/emm-sale/src/docs/asciidoc/index.adoc
  backend/emm-sale/src/main/java/com/emmsale/event/api/RecruitmentPostApi.java
  backend/emm-sale/src/main/java/com/emmsale/event/application/RecruitmentPostQueryService.java
  backend/emm-sale/src/main/resources/http/event.http
  backend/emm-sale/src/test/java/com/emmsale/event/api/RecruitmentPostApiTest.java
  backend/emm-sale/src/test/java/com/emmsale/event/application/RecruitmentPostQueryServiceTest.java
Labels: 백엔드, 기능 추가, High Priority

#331 Feature/#312 함께 가기 알림 요청 보냈는지 확인하는 api
  backend/emm-sale/.gitignore
  backend/emm-sale/src/docs/asciidoc/index.adoc
  backend/emm-sale/src/main/java/com/emmsale/notification/api/RequestNotificationApi.java
  backend/emm-sale/src/main/java/com/emmsale/notification/application/RequestNotificationQueryService.java
  backend/emm-sale/src/main/java/com/emmsale/notification/application/dto/RequestNotificationExistedRequest.java
  backend/emm-sale/src/main/resources/http/request-notification.http
  backend/emm-sale/src/main/resources/static/docs/index.html
  backend/emm-sale/src/test/java/com/emmsale/notification/api/RequestNotificationApiTest.java
  backend/emm-sale/src/test/java/com/emmsale/notification/application/RequestNotificationQueryServiceTest.java
Labels: 백엔드, 기능 추가, High Priority

#342 hotfix : api 문서에서 queryParam 값들을 카멜 케이스로 받아오도록 수정
  backend/emm-sale/src/test/java/com/emmsale/notification/api/RequestNotificationApiTest.java
  backend/emm-sale/src/test/java/com/emmsale/notification/api/UpdateNotificationApiTest.java
Labels: 버그, 백엔드, High Priority

#343 feat(SettingFragment): 설정 화면 틀 구현
  android/2023-emmsale/app/src/main/java/com/emmsale/data/member/MemberRepository.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/member/MemberRepositoryImpl.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/member/MemberService.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/token/TokenRepository.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/token/TokenRepositoryImpl.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/views/VerticalDivider.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/setting/SettingFragment.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/setting/SettingViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/setting/uiState/MemberUiState.kt
  android/2023-emmsale/app/src/main/res/drawable/bg_setting_button.xml
  android/2023-emmsale/app/src/main/res/drawable/ic_setting_button_decoration.xml
  android/2023-emmsale/app/src/main/res/layout/fragment_my_profile.xml
  android/2023-emmsale/app/src/main/res/layout/fragment_setting.xml
  android/2023-emmsale/app/src/main/res/values/strings.xml
Labels: 안드로이드, 기능 추가, High Priority

#350 refactor: 전체 필터링 옵션 초기화 버튼 아이콘 및 배치 변경
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/conferenceFilter/ConferenceFilterActivity.kt
  android/2023-emmsale/app/src/main/res/drawable/ic_conference_filter_clear.xml
  android/2023-emmsale/app/src/main/res/layout/activity_conference_filter.xml
  android/2023-emmsale/app/src/main/res/menu/menu_conference_filter.xml
  android/2023-emmsale/app/src/main/res/values/strings.xml
Labels: 안드로이드, Low Priority

#351 Feature/#322 온보딩 화면 뒤로가기 버튼 추가
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/onboarding/OnboardingActivity.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/onboarding/club/OnboardingClubFragment.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/onboarding/education/OnboardingEducationFragment.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/onboarding/field/OnboardingFieldFragment.kt
  android/2023-emmsale/app/src/main/res/layout/fragment_onboarding_club.xml
  android/2023-emmsale/app/src/main/res/layout/fragment_onboarding_education.xml
  android/2023-emmsale/app/src/main/res/layout/fragment_onboarding_field.xml
  android/2023-emmsale/app/src/main/res/values/strings.xml
Labels: 안드로이드, Low Priority

#352 feat: 관심 카테고리 선택 개수를 4개로 제한
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/extension/ContextExt.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/extension/FragmentExt.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/onboarding/OnboardingViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/onboarding/field/OnboardingFieldFragment.kt
  android/2023-emmsale/app/src/main/res/values/strings.xml
Labels: 안드로이드, Low Priority

#355 feat: 함께해요 요청 알림에서 카카오톡 오픈 채팅으로 이동하는 기능 구현
  android/2023-emmsale/app/src/main/java/com/emmsale/data/member/Member.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/member/dto/MemberApiModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/member/mapper/MemberMapper.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/notificationBox/recruitmentNotification/RecruitmentNotificationFragment.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/notificationBox/recruitmentNotification/RecruitmentNotificationViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/notificationBox/recruitmentNotification/recyclerview/body/RecruitmentNotificationBodyClickListener.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/notificationBox/recruitmentNotification/uistate/RecruitmentNotificationBodyUiState.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/notificationBox/recruitmentNotification/uistate/RecruitmentNotificationMemberUiState.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/onboarding/field/OnboardingFieldFragment.kt
  android/2023-emmsale/app/src/main/res/layout/item_recruitment_notification_body.xml
  android/2023-emmsale/app/src/main/res/values/strings.xml
Labels: 안드로이드, Low Priority

#354 Feature/#353 멤버 단건조회 필드 추가
  backend/emm-sale/src/main/java/com/emmsale/member/application/MemberQueryService.java
  backend/emm-sale/src/main/java/com/emmsale/member/application/dto/MemberProfileResponse.java
  backend/emm-sale/src/test/java/com/emmsale/member/api/MemberApiTest.java
  backend/emm-sale/src/test/java/com/emmsale/member/application/MemberQueryServiceTest.java
Labels: 백엔드, 기능 추가, High Priority

#359 Feature/#301 사용자 차단목록 관리
  android/2023-emmsale/app/src/main/AndroidManifest.xml
  android/2023-emmsale/app/src/main/java/com/emmsale/data/blockedMember/BlockedMember.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/blockedMember/BlockedMemberRepository.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/blockedMember/BlockedMemberRepositoryImpl.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/blockedMember/BlockedMemberService.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/blockedMember/dto/BlockedMemberApiModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/blockedMember/mapper/BlockedMemberMapper.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/di/RepositoryContainer.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/di/ServiceContainer.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/livedata/NotNullLiveData.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/views/ConfirmDialog.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/service/KerdyFirebaseMessagingService.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/setting/block/MemberBlockActivity.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/setting/block/MemberBlockViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/setting/block/recyclerview/BlockedMemberAdapter.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/setting/block/recyclerview/BlockedMemberDiffUtil.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/setting/block/recyclerview/BlockedMemberViewHolder.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/setting/block/uistate/BlockedMemberUiState.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/setting/block/uistate/BlockedMembersUiState.kt
  android/2023-emmsale/app/src/main/res/drawable/bg_block_member_button.xml
  android/2023-emmsale/app/src/main/res/drawable/ic_all_close.xml
  android/2023-emmsale/app/src/main/res/layout/activity_member_block.xml
  android/2023-emmsale/app/src/main/res/layout/dialog_confirm.xml
  android/2023-emmsale/app/src/main/res/layout/item_block_member.xml
  android/2023-emmsale/app/src/main/res/menu/menu_member_block.xml
  android/2023-emmsale/app/src/main/res/values/strings.xml
Labels: 안드로이드, Low Priority

#362 Feature/#316 댓글 수정 기능 구현
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/CommentFragment.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/CommentViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/childComment/ChildCommentActivity.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/childComment/ChildCommentViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/childComment/recyclerView/ChildCommentAdapter.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/childComment/recyclerView/ChildCommentViewHolder.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/childComment/recyclerView/ParentCommentViewHolder.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/childComment/uiState/ChildCommentsUiState.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/childComment/uiState/CommentUiState.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/recyclerView/CommentViewHolder.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/recyclerView/CommentsAdapter.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/uiState/CommentUiState.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/uiState/CommentsUiState.kt
  android/2023-emmsale/app/src/main/res/color/all_enable_primary.xml
  android/2023-emmsale/app/src/main/res/layout/activity_child_comments.xml
  android/2023-emmsale/app/src/main/res/layout/activity_edit_my_profile.xml
  android/2023-emmsale/app/src/main/res/layout/fragment_comments.xml
Labels: 안드로이드, 기능 추가

#348 feat : UpdateNotification 단건 & 다건 삭제 API 구현
  backend/emm-sale/src/docs/asciidoc/index.adoc
  backend/emm-sale/src/main/java/com/emmsale/notification/api/UpdateNotificationApi.java
  backend/emm-sale/src/main/java/com/emmsale/notification/application/UpdateNotificationCommandService.java
  backend/emm-sale/src/main/java/com/emmsale/notification/application/dto/UpdateNotificationDeleteRequest.java
  backend/emm-sale/src/main/java/com/emmsale/notification/domain/UpdateNotification.java
  backend/emm-sale/src/main/java/com/emmsale/notification/domain/UpdateNotificationRepository.java
  backend/emm-sale/src/test/java/com/emmsale/notification/api/UpdateNotificationApiTest.java
  backend/emm-sale/src/test/java/com/emmsale/notification/application/UpdateNotificationCommandServiceTest.java
  backend/emm-sale/src/test/java/com/emmsale/notification/domain/UpdateNotificationRepositoryTest.java
Labels: 백엔드, 기능 추가, High Priority

#272 Feature/#245 유저 게시글 신고하기 및 신고함 조회 기능
  backend/emm-sale/src/docs/asciidoc/index.adoc
  backend/emm-sale/src/main/java/com/emmsale/comment/domain/Comment.java
  backend/emm-sale/src/main/java/com/emmsale/event/domain/RecruitmentPost.java
  backend/emm-sale/src/main/java/com/emmsale/member/domain/Member.java
  backend/emm-sale/src/main/java/com/emmsale/notification/domain/RequestNotification.java
  backend/emm-sale/src/main/java/com/emmsale/report/api/ReportApi.java
  backend/emm-sale/src/main/java/com/emmsale/report/application/ReportCommandService.java
  backend/emm-sale/src/main/java/com/emmsale/report/application/ReportQueryService.java
  backend/emm-sale/src/main/java/com/emmsale/report/application/dto/ReportCreateRequest.java
  backend/emm-sale/src/main/java/com/emmsale/report/application/dto/ReportCreateResponse.java
  backend/emm-sale/src/main/java/com/emmsale/report/application/dto/ReportFindResponse.java
  backend/emm-sale/src/main/java/com/emmsale/report/domain/Report.java
  backend/emm-sale/src/main/java/com/emmsale/report/domain/ReportType.java
  backend/emm-sale/src/main/java/com/emmsale/report/domain/repository/ReportRepository.java
  backend/emm-sale/src/main/java/com/emmsale/report/exception/ReportException.java
  backend/emm-sale/src/main/java/com/emmsale/report/exception/ReportExceptionType.java
  backend/emm-sale/src/main/resources/data.sql
  backend/emm-sale/src/main/resources/http/report.http
  backend/emm-sale/src/main/resources/schema.sql
  backend/emm-sale/src/test/java/com/emmsale/report/api/ReportApiTest.java
  backend/emm-sale/src/test/java/com/emmsale/report/application/ReportCommandServiceTest.java
  backend/emm-sale/src/test/java/com/emmsale/report/application/ReportQueryServiceTest.java
  backend/emm-sale/src/test/resources/data-test.sql
Labels: 백엔드, 기능 추가, High Priority

#363 Feature/#284-반환 데이터의 날짜 포맷을 하나로 통일
  backend/emm-sale/src/main/java/com/emmsale/comment/application/dto/CommentResponse.java
  backend/emm-sale/src/main/java/com/emmsale/event/application/dto/EventDetailRequest.java
  backend/emm-sale/src/main/java/com/emmsale/event/application/dto/RecruitmentPostResponse.java
  backend/emm-sale/src/test/java/com/emmsale/event/api/EventApiTest.java
Labels: 백엔드, 기능 추가

#320 Feature/#276 차단된 사용자의 알림 차단
  backend/emm-sale/src/docs/asciidoc/index.adoc
  backend/emm-sale/src/main/java/com/emmsale/notification/api/RequestNotificationApi.java
  backend/emm-sale/src/main/java/com/emmsale/notification/application/RequestNotificationCommandService.java
  backend/emm-sale/src/main/java/com/emmsale/notification/exception/NotificationExceptionType.java
  backend/emm-sale/src/main/resources/static/docs/index.html
  backend/emm-sale/src/test/java/com/emmsale/notification/api/RequestNotificationApiTest.java
  backend/emm-sale/src/test/java/com/emmsale/notification/application/RequestNotificationCommandServiceTest.java
Labels: 백엔드, 기능 추가, Low Priority

#364 Feature/#357 사용자 차단 목록 조회
  backend/emm-sale/src/docs/asciidoc/index.adoc
  backend/emm-sale/src/main/java/com/emmsale/block/api/BlockApi.java
  backend/emm-sale/src/main/java/com/emmsale/block/application/BlockQueryService.java
  backend/emm-sale/src/main/java/com/emmsale/block/application/dto/BlockResponse.java
  backend/emm-sale/src/test/java/com/emmsale/block/api/BlockApiTest.java
  backend/emm-sale/src/test/java/com/emmsale/block/application/BlockQueryServiceTest.java
Labels: 백엔드, 기능 추가, High Priority

#369 Feature/#366 MemberActivity 수정 API 구현
  backend/emm-sale/src/docs/asciidoc/index.adoc
  backend/emm-sale/src/test/java/com/emmsale/member/api/MemberApiTest.java
Labels: 백엔드, 리팩터링, High Priority

#370 Feature/#338 작성한 댓글 목록 화면
  android/2023-emmsale/app/src/main/AndroidManifest.xml
  android/2023-emmsale/app/src/main/java/com/emmsale/data/comment/Comment.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/comment/CommentRepository.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/comment/CommentRepositoryImpl.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/comment/mapper/CommentMapper.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/setting/SettingFragment.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/setting/SettingViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/setting/myComments/MyCommentsActivity.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/setting/myComments/MyCommentsViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/setting/myComments/recyclerView/MyCommentViewHolder.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/setting/myComments/recyclerView/MyCommentsAdapter.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/setting/myComments/uiState/MyCommentUiState.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/setting/myComments/uiState/MyCommentsUiState.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/setting/uiState/MemberUiState.kt
  android/2023-emmsale/app/src/main/res/layout/activity_my_comments.xml
  android/2023-emmsale/app/src/main/res/layout/item_mycomments_comment.xml
  android/2023-emmsale/app/src/main/res/values/strings.xml
Labels: 안드로이드, 기능 추가, Low Priority

#374 Feature/#336 알림 설정 화면 구현
  android/2023-emmsale/app/src/main/AndroidManifest.xml
  android/2023-emmsale/app/src/main/java/com/emmsale/data/config/Config.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/config/ConfigRepository.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/config/ConfigRepositoryImpl.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/eventTag/EventTagRepository.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/eventTag/EventTagRepositoryImpl.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/eventTag/EventTagService.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/eventTag/FakeEventTagService.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/eventTag/local/EventTagLocalDataSource.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/eventTag/mapper/EventTag.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/eventTag/remote/EventTagRemoteDataSource.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/eventTag/remote/EventTagService.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/eventTag/remote/dto/EventTagApiModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/token/TokenRepositoryImpl.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/di/LocalDataSourceContainer.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/di/RemoteDataSourceContainer.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/di/RepositoryContainer.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/di/ServiceContainer.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/KerdyApplication.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/views/bottomMenuDialog/MenuItemType.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/service/KerdyFirebaseMessagingService.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/competition/CompetitionViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/conference/ConferenceViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/setting/SettingFragment.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/setting/block/MemberBlockActivity.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/setting/notificationConfig/NotificationConfigActivity.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/setting/notificationConfig/NotificationConfigViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/setting/notificationConfig/uistate/NotificationConfigUiState.kt
  android/2023-emmsale/app/src/main/res/drawable/bg_editmyprofile_activity_add_button.xml
  android/2023-emmsale/app/src/main/res/drawable/bg_editmyprofile_interest_tag.xml
  android/2023-emmsale/app/src/main/res/drawable/bg_notification_switch_track_off.xml
  android/2023-emmsale/app/src/main/res/drawable/bg_notification_switch_track_on.xml
  android/2023-emmsale/app/src/main/res/drawable/bg_notificationconfig_add.xml
  android/2023-emmsale/app/src/main/res/drawable/bg_notificationconfig_config.xml
  android/2023-emmsale/app/src/main/res/drawable/bg_notificationconfig_switch_thumb.xml
  android/2023-emmsale/app/src/main/res/drawable/bg_notificationconfig_switch_track.xml
  android/2023-emmsale/app/src/main/res/drawable/ic_editmyprofile_remove_button.xml
  android/2023-emmsale/app/src/main/res/drawable/ic_myprofile_edit_mode_button.xml
  android/2023-emmsale/app/src/main/res/drawable/ic_notificationconfig_add_icon.xml
  android/2023-emmsale/app/src/main/res/drawable/img_editmyprofile_activity_add_button.xml
  android/2023-emmsale/app/src/main/res/layout/activity_child_comments.xml
  android/2023-emmsale/app/src/main/res/layout/activity_edit_my_profile.xml
  android/2023-emmsale/app/src/main/res/layout/activity_member_block.xml
  android/2023-emmsale/app/src/main/res/layout/activity_my_comments.xml
  android/2023-emmsale/app/src/main/res/layout/activity_notification_config.xml
  android/2023-emmsale/app/src/main/res/layout/fragment_comments.xml
  android/2023-emmsale/app/src/main/res/layout/fragment_editmyprofile_clubs_add_bottom_dialog.xml
  android/2023-emmsale/app/src/main/res/layout/fragment_editmyprofile_educations_add_bottom_dialog.xml
  android/2023-emmsale/app/src/main/res/layout/fragment_editmyprofile_fields_add_bottom_dialog.xml
  android/2023-emmsale/app/src/main/res/layout/fragment_my_profile.xml
  android/2023-emmsale/app/src/main/res/layout/item_editmyprofile_activity.xml
  android/2023-emmsale/app/src/main/res/layout/item_editmyprofile_field.xml
  android/2023-emmsale/app/src/main/res/layout/item_mycomments_comment.xml
  android/2023-emmsale/app/src/main/res/menu/menu_notification_config.xml
  android/2023-emmsale/app/src/main/res/values/strings.xml
Labels: 안드로이드, Low Priority

#368 사용자 목록 차단 해제 API
  backend/emm-sale/src/docs/asciidoc/index.adoc
  backend/emm-sale/src/main/java/com/emmsale/block/api/BlockApi.java
  backend/emm-sale/src/main/java/com/emmsale/block/application/BlockCommandService.java
  backend/emm-sale/src/main/java/com/emmsale/block/domain/Block.java
  backend/emm-sale/src/main/java/com/emmsale/block/exception/BlockExceptionType.java
  backend/emm-sale/src/test/java/com/emmsale/block/api/BlockApiTest.java
  backend/emm-sale/src/test/java/com/emmsale/block/application/BlockCommandServiceTest.java
Labels: 백엔드, 기능 추가, High Priority

#375 feat : 난독화 코드 적용
  android/2023-emmsale/app/build.gradle.kts
  android/2023-emmsale/app/proguard-rules.pro
Labels: 안드로이드, High Priority

#376 Feature/#367 사용자 단건 조회 시 GitHub id 반환하도록 수정
  backend/emm-sale/src/main/java/com/emmsale/login/application/dto/GithubProfileResponse.java
  backend/emm-sale/src/main/java/com/emmsale/member/application/dto/MemberProfileResponse.java
  backend/emm-sale/src/main/java/com/emmsale/member/domain/Member.java
  backend/emm-sale/src/main/resources/data.sql
  backend/emm-sale/src/main/resources/schema.sql
  backend/emm-sale/src/test/java/com/emmsale/comment/application/CommentCommandServiceTest.java
  backend/emm-sale/src/test/java/com/emmsale/event/application/RecruitmentPostCommandServiceTest.java
  backend/emm-sale/src/test/java/com/emmsale/event/application/RecruitmentPostQueryServiceTest.java
  backend/emm-sale/src/test/java/com/emmsale/event/domain/EventTest.java
  backend/emm-sale/src/test/java/com/emmsale/event/domain/RecruitmentPostTest.java
  backend/emm-sale/src/test/java/com/emmsale/member/MemberFixture.java
  backend/emm-sale/src/test/java/com/emmsale/member/api/MemberApiTest.java
  backend/emm-sale/src/test/java/com/emmsale/member/application/MemberQueryServiceTest.java
  backend/emm-sale/src/test/resources/data-test.sql
Labels: 백엔드, 기능 추가

#381 Feature/#372 프로필 수정 기능 api 연결
  android/2023-emmsale/app/src/main/java/com/emmsale/data/member/Member.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/member/MemberRepository.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/member/MemberRepositoryImpl.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/member/MemberService.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/member/dto/MemberActivitiesUpdateRequestBody.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/member/dto/MemberApiModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/member/mapper/MemberMapper.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/livedata/error/ErrorClearLiveData.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/livedata/error/ErrorEvent.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/livedata/error/ErrorSetLiveData.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/views/BottomDialogMenuItem.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/views/BottomMenuDialog.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/recruitment/detail/RecruitmentPostDetailActivity.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/myProfile/MyProfileFragment.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/myProfile/MyProfileViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/myProfile/editMyProfile/EditMyProfileActivity.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/myProfile/editMyProfile/EditMyProfileViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/myProfile/editMyProfile/uiState/EditMyProfileErrorEvent.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/myProfile/uiState/MyProfileErrorEvent.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/setting/uiState/MemberUiState.kt
  android/2023-emmsale/app/src/main/res/layout/activity_child_comments.xml
  android/2023-emmsale/app/src/main/res/layout/fragment_comments.xml
  android/2023-emmsale/app/src/main/res/layout/fragment_setting.xml
  android/2023-emmsale/app/src/main/res/values/strings.xml
Labels: 안드로이드, 기능 추가, Low Priority

#392 Feature/#330 신고하기 기능 추가
  android/2023-emmsale/app/src/main/java/com/emmsale/data/comment/CommentRepository.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/comment/CommentRepositoryImpl.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/comment/CommentService.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/member/MemberRepository.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/member/MemberRepositoryImpl.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/member/MemberService.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/member/dto/BlockRequestBody.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/notification/NotificationRepository.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/notification/NotificationRepositoryImpl.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/notification/NotificationService.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/recruitment/RecruitmentRepository.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/recruitment/RecruitmentRepositoryImpl.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/recruitment/RecruitmentService.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/report/dto/ReportApiModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/report/dto/ReportRequestBody.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/views/InfoDialog.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/CommentFragment.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/CommentViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/childComment/ChildCommentActivity.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/childComment/ChildCommentViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/childComment/recyclerView/ChildCommentAdapter.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/childComment/recyclerView/ChildCommentViewHolder.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/childComment/recyclerView/ParentCommentViewHolder.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/childComment/uiState/ChildCommentsEvent.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/childComment/uiState/ChildCommentsUiState.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/childComment/uiState/CommentUiState.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/recyclerView/CommentViewHolder.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/recyclerView/CommentsAdapter.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/uiState/CommentUiState.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/uiState/CommentsEvent.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/recruitment/detail/RecruitmentPostDetailActivity.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/recruitment/detail/RecruitmentPostDetailViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/recruitment/detail/uiState/RecruitmentPostDetailEvent.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/notificationBox/recruitmentNotification/RecruitmentNotificationFragment.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/notificationBox/recruitmentNotification/RecruitmentNotificationViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/notificationBox/recruitmentNotification/uistate/RecruitmentNotificationEvent.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/profile/ProfileActivity.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/profile/ProfileViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/profile/uiState/ProfileEvent.kt
  android/2023-emmsale/app/src/main/res/layout/dialog_info.xml
  android/2023-emmsale/app/src/main/res/values/strings.xml
Labels: 안드로이드, 기능 추가, Low Priority

#386 Feature/#379 내가 작성한 댓글 조회 api 구현
  backend/emm-sale/src/main/java/com/emmsale/comment/api/CommentApi.java
  backend/emm-sale/src/main/java/com/emmsale/comment/application/CommentQueryService.java
  backend/emm-sale/src/main/java/com/emmsale/comment/application/dto/CommentFindRequest.java
  backend/emm-sale/src/main/java/com/emmsale/comment/application/dto/CommentHierarchyResponse.java
  backend/emm-sale/src/main/java/com/emmsale/comment/application/dto/CommentResponse.java
  backend/emm-sale/src/main/java/com/emmsale/comment/domain/CommentRepository.java
  backend/emm-sale/src/main/java/com/emmsale/comment/exception/CommentExceptionType.java
  backend/emm-sale/src/test/java/com/emmsale/comment/api/CommentApiTest.java
  backend/emm-sale/src/test/java/com/emmsale/comment/application/CommentQueryServiceTest.java
  backend/emm-sale/src/test/java/com/emmsale/comment/domain/CommentRepositoryTest.java
Labels: 백엔드, 기능 추가, High Priority

#397 Feature/#360 행사 알림 태그 선택
  android/2023-emmsale/app/src/main/AndroidManifest.xml
  android/2023-emmsale/app/src/main/java/com/emmsale/data/common/ApiResult.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/eventTag/EventTagRepository.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/eventTag/EventTagRepositoryImpl.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/eventTag/local/EventTagLocalDataSource.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/eventTag/remote/EventTagRemoteDataSource.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/eventTag/remote/EventTagService.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/eventTag/remote/dto/InterestEventTagUpdateRequestApiModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/eventTag/remote/dto/InterestEventTagUpdateResponseApiModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/notification/NotificationService.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/di/ServiceContainer.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/extension/ContextExt.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/views/CancelablePrimaryTag.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/setting/SettingFragment.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/setting/notification/NotificationConfigActivity.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/setting/notification/NotificationConfigViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/setting/notification/uistate/NotificationConfigUiState.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/setting/notification/uistate/NotificationTagUiState.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/setting/notification/uistate/NotificationTagsUiState.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/setting/notificationConfig/NotificationConfigActivity.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/setting/notificationConfig/NotificationConfigViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/setting/notificationTagConfig/NotificationTagConfigActivity.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/setting/notificationTagConfig/NotificationTagConfigViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/setting/notificationTagConfig/uistate/NotificationTagConfigUiState.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/setting/notificationTagConfig/uistate/NotificationTagsConfigUiState.kt
  android/2023-emmsale/app/src/main/res/drawable/bg_cancelable_primary_tag.xml
  android/2023-emmsale/app/src/main/res/drawable/ic_all_scrap_checked.xml
  android/2023-emmsale/app/src/main/res/drawable/ic_all_scrap_unchecked.xml
  android/2023-emmsale/app/src/main/res/drawable/ic_cancelable_close.xml
  android/2023-emmsale/app/src/main/res/layout/activity_child_comments.xml
  android/2023-emmsale/app/src/main/res/layout/activity_event_detail.xml
  android/2023-emmsale/app/src/main/res/layout/activity_notification_config.xml
  android/2023-emmsale/app/src/main/res/layout/activity_notification_tag_config.xml
  android/2023-emmsale/app/src/main/res/layout/activity_recruitment_post_detail.xml
  android/2023-emmsale/app/src/main/res/layout/activity_recruitment_post_writing.xml
  android/2023-emmsale/app/src/main/res/layout/dialog_info.xml
  android/2023-emmsale/app/src/main/res/layout/fragment_comments.xml
  android/2023-emmsale/app/src/main/res/layout/fragment_event_information.xml
  android/2023-emmsale/app/src/main/res/layout/fragment_scrapped_event.xml
  android/2023-emmsale/app/src/main/res/layout/fragment_setting.xml
  android/2023-emmsale/app/src/main/res/layout/item_childcomments_childcomment.xml
  android/2023-emmsale/app/src/main/res/layout/item_childcomments_parentcomment.xml
  android/2023-emmsale/app/src/main/res/layout/item_comments_comments.xml
  android/2023-emmsale/app/src/main/res/values/strings.xml
Labels: 안드로이드

#401 Fix#339 태그 알림에서 관심 태그를 불러오지 못하는 버그 수정
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/setting/notificationTagConfig/NotificationTagConfigViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/setting/notificationTagConfig/uistate/NotificationTagsConfigUiState.kt
Labels: 버그, 안드로이드, Low Priority

#404 Feature/#400 댓글 조회 api에 맞게 수정
  android/2023-emmsale/app/src/main/java/com/emmsale/data/comment/Comment.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/comment/CommentRepositoryImpl.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/comment/CommentService.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/comment/dto/CommentApiModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/comment/mapper/CommentMapper.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/setting/myComments/MyCommentsActivity.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/setting/myComments/MyCommentsViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/setting/myComments/recyclerView/MyCommentViewHolder.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/setting/myComments/uiState/MyCommentUiState.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/setting/myComments/uiState/MyCommentsUiState.kt
Labels: 안드로이드, 기능 추가, High Priority

#380 fix: 중복된 활동 id 오류 수정
  backend/emm-sale/src/main/java/com/emmsale/member/api/MemberApi.java
  backend/emm-sale/src/main/java/com/emmsale/member/application/MemberActivityService.java
  backend/emm-sale/src/test/java/com/emmsale/member/api/MemberApiTest.java
  backend/emm-sale/src/test/java/com/emmsale/member/application/MemberActivityServiceTest.java
Labels: 버그, 백엔드, High Priority

#388 Feature/#383 사용자 관심 태그 업데이트 기능 구현
  backend/emm-sale/src/docs/asciidoc/index.adoc
  backend/emm-sale/src/main/java/com/emmsale/member/api/InterestTagApi.java
  backend/emm-sale/src/main/java/com/emmsale/member/application/InterestTagService.java
  backend/emm-sale/src/main/java/com/emmsale/member/application/dto/InterestTagUpdateRequest.java
  backend/emm-sale/src/main/java/com/emmsale/member/domain/InterestTagRepository.java
  backend/emm-sale/src/test/java/com/emmsale/member/api/InterestTagApiTest.java
  backend/emm-sale/src/test/java/com/emmsale/member/application/InterestTagServiceTest.java
  backend/emm-sale/src/test/java/com/emmsale/member/domain/InterestTagRepositoryTest.java
Labels: 백엔드, 기능 추가, High Priority

#390 Feature/#389 스크랩을 이벤트의 id로 삭제할 수 있도록 api 수정
  backend/emm-sale/src/main/java/com/emmsale/scrap/api/ScrapApi.java
  backend/emm-sale/src/main/java/com/emmsale/scrap/application/ScrapCommandService.java
  backend/emm-sale/src/main/java/com/emmsale/scrap/domain/ScrapRepository.java
  backend/emm-sale/src/test/java/com/emmsale/scrap/api/ScrapApiTest.java
  backend/emm-sale/src/test/java/com/emmsale/scrap/application/ScrapCommandServiceTest.java
  backend/emm-sale/src/test/java/com/emmsale/scrap/domain/ScrapRepositoryTest.java
Labels: 백엔드, 리팩터링, High Priority

#405 Feature/#287 스프링 로그 모니터링 구성
  backend/emm-sale/src/main/java/com/emmsale/GlobalControllerAdvice.java
  backend/emm-sale/src/main/resources/logback.xml
Labels: 백엔드, 환경 설정, High Priority

#416 Feature/#413 prod 배포 스크립트 수정
  .github/workflows/backend-prod-deploy.yml
Labels: 백엔드, 환경 설정, High Priority

#419 Fix/#415 작성한 댓글의 내용이 아닌 부모의 댓글이 조회되는 현상 해결
  backend/emm-sale/src/docs/asciidoc/index.adoc
  backend/emm-sale/src/main/java/com/emmsale/comment/application/CommentQueryService.java
  backend/emm-sale/src/main/java/com/emmsale/comment/event/UpdateNotificationEvent.java
  backend/emm-sale/src/main/java/com/emmsale/notification/application/dto/UpdateNotificationResponse.java
  backend/emm-sale/src/test/java/com/emmsale/comment/api/CommentApiTest.java
  backend/emm-sale/src/test/java/com/emmsale/comment/application/CommentCommandServiceTest.java
  backend/emm-sale/src/test/java/com/emmsale/comment/application/CommentQueryServiceTest.java
  backend/emm-sale/src/test/java/com/emmsale/notification/api/UpdateNotificationApiTest.java
  backend/emm-sale/src/test/java/com/emmsale/notification/application/UpdateNotificationQueryServiceTest.java
Labels: 버그, 백엔드, High Priority

#420 Feature/#418 톰캣, 도커 타임존 설정
  .github/workflows/backend-dev-deploy.yml
  .github/workflows/backend-prod-deploy.yml
  backend/emm-sale/Dockerfile-dev
  backend/emm-sale/Dockerfile-prod
Labels: 백엔드, 환경 설정, High Priority

#410 feat : 대대댓글일 경우 Exception 발생
  backend/emm-sale/src/main/java/com/emmsale/comment/domain/Comment.java
  backend/emm-sale/src/main/java/com/emmsale/comment/exception/CommentExceptionType.java
  backend/emm-sale/src/test/java/com/emmsale/comment/domain/CommentTest.java
Labels: 백엔드, 기능 추가

#421 feat: 사용자의 모든 함께가기 요청 조회 api 구현
  backend/emm-sale/src/docs/asciidoc/index.adoc
  backend/emm-sale/src/main/java/com/emmsale/event/api/RecruitmentPostApi.java
  backend/emm-sale/src/main/java/com/emmsale/event/application/RecruitmentPostQueryService.java
  backend/emm-sale/src/main/java/com/emmsale/event/application/dto/RecruitmentPostQueryResponse.java
  backend/emm-sale/src/main/java/com/emmsale/event/domain/repository/RecruitmentPostRepository.java
  backend/emm-sale/src/test/java/com/emmsale/event/api/RecruitmentPostApiTest.java
  backend/emm-sale/src/test/java/com/emmsale/event/application/RecruitmentPostQueryServiceTest.java
  backend/emm-sale/src/test/java/com/emmsale/event/domain/repository/RecruitmentPostRepositoryTest.java
Labels: 백엔드, 기능 추가, High Priority

#427 fix(MemberService): 회원의 활동 삭제 api 수정
  android/2023-emmsale/app/src/main/java/com/emmsale/data/member/MemberService.kt
Labels: 버그, 안드로이드, High Priority

#428 refactor: 함께가기 요청 목록 반환 dto 수정
  backend/emm-sale/src/main/java/com/emmsale/event/application/dto/RecruitmentPostQueryResponse.java
  backend/emm-sale/src/test/java/com/emmsale/event/api/RecruitmentPostApiTest.java
Labels: 백엔드, 리팩터링, High Priority

#433 Fix/#412 알림 리다이렉트 후 뒤로가기 처리
  android/2023-emmsale/app/src/main/AndroidManifest.xml
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/service/KerdyFirebaseMessagingService.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/EventDetailActivity.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/childComment/ChildCommentActivity.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/MainActivity.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/myProfile/editMyProfile/EditMyProfileViewModel.kt
Labels: 안드로이드, 기능 추가, Low Priority

#437 Feature/#408 스플래시 화면 구현
  android/2023-emmsale/app/build.gradle.kts
  android/2023-emmsale/app/src/main/AndroidManifest.xml
  android/2023-emmsale/app/src/main/java/com/emmsale/data/common/AuthInterceptor.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/common/ServiceFactory.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/config/Config.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/config/ConfigRepository.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/config/ConfigRepositoryImpl.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/token/TokenRepositoryImpl.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/recruitment/detail/RecruitmentPostDetailActivity.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/login/LoginActivity.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/login/LoginViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/MainActivity.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/splash/SplashActivity.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/splash/SplashViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/splash/uistate/SplashUiState.kt
  android/2023-emmsale/app/src/main/res/layout/activity_my_post.xml
  android/2023-emmsale/app/src/main/res/layout/activity_splash.xml
  android/2023-emmsale/app/src/main/res/layout/activity_use_term_web_view.xml
  android/2023-emmsale/app/src/main/res/layout/item_my_post.xml
  android/2023-emmsale/app/src/main/res/values-v31/themes.xml
Labels: 안드로이드, Low Priority

#444 Fix/#434 이전 알림 재사용 버그 수정
  android/2023-emmsale/app/src/main/java/com/emmsale/data/common/ServiceFactory.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/extension/ContextExt.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/service/KerdyFirebaseMessagingService.kt
Labels: 버그, 안드로이드, High Priority

#448 Feature/#371 안드로이드 로그 설계 적용
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/KerdyApplication.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/firebase/analytics/FirebaseAnalyticsDelegate.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/firebase/analytics/FirebaseAnalyticsDelegateImpl.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/firebase/analytics/KerdyAnalytics.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/firebase/analytics/KerdyEvent.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/firebase/analytics/KerdyParam.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/EventDetailActivity.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/EventDetailViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/CommentFragment.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/CommentViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/information/EventInfoFragment.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/recruitment/EventRecruitmentFragment.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/recruitment/detail/RecruitmentPostDetailViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/recruitment/writing/RecruitmentPostWritingViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/login/LoginActivity.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/setting/SettingFragment.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/setting/notification/NotificationConfigActivity.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/setting/notification/NotificationConfigViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/setting/notificationTagConfig/NotificationTagConfigActivity.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/setting/notificationTagConfig/NotificationTagConfigViewModel.kt
  android/2023-emmsale/app/src/main/res/layout/activity_open_profile_url_config.xml
  android/2023-emmsale/app/src/main/res/layout/activity_recruitment_post_detail.xml
  android/2023-emmsale/app/src/main/res/layout/fragment_event_information.xml
Labels: 안드로이드, Low Priority

#452 Feature/#451 앱 아이콘 적용
  android/2023-emmsale/app/src/main/ic_launcher-playstore.png
  android/2023-emmsale/app/src/main/res/drawable/bg_login.xml
  android/2023-emmsale/app/src/main/res/drawable/ic_launcher_background.xml
  android/2023-emmsale/app/src/main/res/drawable/ic_launcher_foreground.xml
  android/2023-emmsale/app/src/main/res/layout/activity_login.xml
  android/2023-emmsale/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  android/2023-emmsale/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  android/2023-emmsale/app/src/main/res/mipmap-hdpi/ic_launcher.webp
  android/2023-emmsale/app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  android/2023-emmsale/app/src/main/res/mipmap-mdpi/ic_launcher.webp
  android/2023-emmsale/app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  android/2023-emmsale/app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  android/2023-emmsale/app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  android/2023-emmsale/app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  android/2023-emmsale/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  android/2023-emmsale/app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  android/2023-emmsale/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
Labels: 안드로이드, Low Priority

#457 Feature/#440 프로필 화면 차단해제 추가
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/setting/openProfileUrl/OpenProfileUrlConfigActivity.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/profile/ProfileActivity.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/profile/ProfileViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/profile/uiState/BlockedMemberUiState.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/profile/uiState/ProfileEvent.kt
  android/2023-emmsale/app/src/main/res/layout/item_mycomments_comment.xml
  android/2023-emmsale/app/src/main/res/values/strings.xml
Labels: 안드로이드, 기능 추가, High Priority

#461 Feature/#460 댓글 화면 디자인 변경
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/childComment/ChildCommentActivity.kt
  android/2023-emmsale/app/src/main/res/layout/item_childcomments_childcomment.xml
  android/2023-emmsale/app/src/main/res/layout/item_childcomments_parentcomment.xml
  android/2023-emmsale/app/src/main/res/layout/item_comments_comments.xml
Labels: 안드로이드, 기능 추가, High Priority

#466 Fix/#464 관심 행사 알림 태그 수정 안 되는 버그 수정
  android/2023-emmsale/app/src/main/java/com/emmsale/data/eventTag/remote/dto/InterestEventTagUpdateRequestApiModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/setting/notification/NotificationConfigViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/setting/notificationTagConfig/NotificationTagConfigViewModel.kt
Labels: 안드로이드, Low Priority

#472 Feature/#471-온보딩_이름_글자_수_제한
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/recruitment/EventRecruitmentFragment.kt
  android/2023-emmsale/app/src/main/res/layout/fragment_onboarding_name.xml
Labels: 안드로이드, 기능 추가, High Priority

#473 Feature/#470 회원 가입 완료후 회원가입 페이지 종료
  android/2023-emmsale/app/src/main/AndroidManifest.xml
  android/2023-emmsale/app/src/main/java/com/emmsale/data/common/ServiceFactory.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/bindingadapter/ImageViewBindingAdapter.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/service/KerdyFirebaseMessagingService.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/notificationBox/NotificationBoxActivity.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/onboarding/OnboardingActivity.kt
  android/2023-emmsale/app/src/main/res/drawable/bg_errorscreen_network_error_icon.xml
  android/2023-emmsale/app/src/main/res/drawable/ic_all_network_error.xml
  android/2023-emmsale/app/src/main/res/layout/activity_child_comments.xml
  android/2023-emmsale/app/src/main/res/layout/activity_edit_my_profile.xml
  android/2023-emmsale/app/src/main/res/layout/activity_event_detail.xml
  android/2023-emmsale/app/src/main/res/layout/activity_member_block.xml
  android/2023-emmsale/app/src/main/res/layout/activity_my_comments.xml
  android/2023-emmsale/app/src/main/res/layout/activity_my_post.xml
  android/2023-emmsale/app/src/main/res/layout/activity_profile.xml
  android/2023-emmsale/app/src/main/res/layout/activity_recruitment_post_detail.xml
  android/2023-emmsale/app/src/main/res/layout/fragment_comments.xml
  android/2023-emmsale/app/src/main/res/layout/fragment_competition.xml
  android/2023-emmsale/app/src/main/res/layout/fragment_conference.xml
  android/2023-emmsale/app/src/main/res/layout/fragment_event_information.xml
  android/2023-emmsale/app/src/main/res/layout/fragment_event_recruitment.xml
  android/2023-emmsale/app/src/main/res/layout/fragment_my_profile.xml
  android/2023-emmsale/app/src/main/res/layout/fragment_primary_notification.xml
  android/2023-emmsale/app/src/main/res/layout/fragment_recruitment_notification.xml
  android/2023-emmsale/app/src/main/res/layout/fragment_scrapped_event.xml
  android/2023-emmsale/app/src/main/res/layout/fragment_setting.xml
  android/2023-emmsale/app/src/main/res/layout/item_block_member.xml
  android/2023-emmsale/app/src/main/res/layout/layout_all_error_screen.xml
Labels: 안드로이드, Low Priority

#476 fix: 온보딩 화면에서 뒤로가기 하고 앱 다시 켜면 홈 화면으로 강제 이동하는 버그 수정
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/login/LoginViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/onboarding/OnboardingViewModel.kt
Labels: 버그, 안드로이드, High Priority

#481 Fix/#477 행사상세화면 뒤로가기 로직 수정
  android/2023-emmsale/app/src/main/AndroidManifest.xml
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/bindingadapter/ImageViewBindingAdapter.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/extension/AlertDialogExt.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/common/extension/ContextExt.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/EventDetailActivity.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/EventDetailViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/CommentFragment.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/CommentViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/childComment/ChildCommentActivity.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/childComment/ChildCommentViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/childComment/uiState/ChildCommentsUiState.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/eventdetail/comment/uiState/CommentsUiState.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/MainActivity.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/competitionFilter/CompetitionFilterActivity.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/conferenceFilter/ConferenceFilterActivity.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/setting/SettingViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/setting/notificationTagConfig/NotificationTagConfigActivity.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/setting/notificationTagConfig/NotificationTagConfigViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/setting/notificationTagConfig/uistate/NotificationTagConfigUiEvent.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/setting/notificationTagConfig/uistate/NotificationTagsConfigUiState.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/setting/openProfileUrl/OpenProfileUrlConfigActivity.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/notificationBox/recruitmentNotification/RecruitmentNotificationFragment.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/notificationBox/recruitmentNotification/RecruitmentNotificationViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/notificationBox/recruitmentNotification/recyclerview/body/RecruitmentNotificationBodyClickListener.kt
  android/2023-emmsale/app/src/main/res/drawable/ic_all_notification.xml
  android/2023-emmsale/app/src/main/res/drawable/img_all_loading.xml
  android/2023-emmsale/app/src/main/res/layout/activity_child_comments.xml
  android/2023-emmsale/app/src/main/res/layout/activity_event_detail.xml
  android/2023-emmsale/app/src/main/res/layout/activity_login.xml
  android/2023-emmsale/app/src/main/res/layout/activity_notification_tag_config.xml
  android/2023-emmsale/app/src/main/res/layout/activity_use_term_web_view.xml
  android/2023-emmsale/app/src/main/res/layout/fragment_setting.xml
  android/2023-emmsale/app/src/main/res/layout/item_childcomments_childcomment.xml
  android/2023-emmsale/app/src/main/res/layout/item_childcomments_parentcomment.xml
  android/2023-emmsale/app/src/main/res/layout/item_comments_comments.xml
  android/2023-emmsale/app/src/main/res/layout/item_competition.xml
  android/2023-emmsale/app/src/main/res/layout/item_conference.xml
  android/2023-emmsale/app/src/main/res/layout/item_mycomments_comment.xml
  android/2023-emmsale/app/src/main/res/layout/item_recruitment_notification_body.xml
  android/2023-emmsale/app/src/main/res/layout/item_scrapped_event.xml
  android/2023-emmsale/app/src/main/res/layout/layout_all_error_screen.xml
  android/2023-emmsale/app/src/main/res/values/strings.xml
Labels: 버그, 안드로이드, High Priority

#484 feat: 난독화 적용
  android/2023-emmsale/app/build.gradle.kts
  android/2023-emmsale/app/src/main/AndroidManifest.xml
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/EventFragment.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/myProfile/MyProfileFragment.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/setting/SettingFragment.kt
Labels: 문서, 안드로이드, High Priority

#487 fix: 기존에 온보딩을 마친 유저는 자동 로그인 안 되는 버그 수정
  android/2023-emmsale/app/src/main/java/com/emmsale/data/login/Login.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/login/mapper/LoginMapper.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/login/LoginViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/MainActivity.kt
Labels: 버그, 안드로이드, High Priority

#488 Fix/#486 알림 태그 삭제 및 추가 버그
  android/2023-emmsale/app/build.gradle.kts
  android/2023-emmsale/app/proguard-rules.pro
  android/2023-emmsale/app/src/main/java/com/emmsale/data/common/ServiceFactory.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/setting/notificationTagConfig/NotificationTagConfigActivity.kt
  android/2023-emmsale/app/src/main/res/values/strings.xml
Labels: 버그, 안드로이드, Low Priority

#491 Fix/#489 컨퍼런스 날짜 필터 제거해도 화면 갱신되지 않는 버그
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/competition/CompetitionViewModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/conference/ConferenceViewModel.kt
  android/2023-emmsale/app/src/main/res/layout/fragment_primary_notification.xml
Labels: 버그, 안드로이드, Low Priority

#479 feat : N+1 detector 만들기
  backend/emm-sale/src/main/java/com/emmsale/config/NPlus1DetectorConfig.java
  backend/emm-sale/src/main/java/com/support/ConnectionProxyHandler.java
  backend/emm-sale/src/main/java/com/support/LoggingForm.java
  backend/emm-sale/src/main/java/com/support/NPlus1DetectorAop.java
  backend/emm-sale/src/main/java/com/support/PreparedStatementProxyHandler.java
Labels: 백엔드, 기능 추가

#504 [Bug] 사진 없는 스크랩 목록 조회 불가
  android/2023-emmsale/app/src/main/java/com/emmsale/data/scrap/ScrappedEvent.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/scrap/dto/ScrappedEventApiModel.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/data/scrap/mapper/ScrappedEventMapper.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/scrap/ScrappedEventFragment.kt
  android/2023-emmsale/app/src/main/java/com/emmsale/presentation/ui/main/event/scrap/uistate/ScrappedEventUiState.kt
Labels: 안드로이드
